/**
 * Tournesol API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ContextEnum.
* @enum {}
* @readonly
*/
export default class ContextEnum {
    
        /**
         * value: "RATE"
         * @const
         */
        "RATE" = "RATE";

    
        /**
         * value: "DIS"
         * @const
         */
        "DIS" = "DIS";

    
        /**
         * value: "INC"
         * @const
         */
        "INC" = "INC";

    

    /**
    * Returns a <code>ContextEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ContextEnum} The enum <code>ContextEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

