/**
 * Tournesol API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Degree model module.
 * @module model/Degree
 * @version 2.0.0
 */
class Degree {
    /**
     * Constructs a new <code>Degree</code>.
     * Degree
     * @alias module:model/Degree
     * @param level {String} Degree level
     * @param domain {String} Degree domain
     * @param institution {String} Degree institution
     */
    constructor(level, domain, institution) { 
        
        Degree.initialize(this, level, domain, institution);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, level, domain, institution) { 
        obj['level'] = level;
        obj['domain'] = domain;
        obj['institution'] = institution;
    }

    /**
     * Constructs a <code>Degree</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Degree} obj Optional instance to populate.
     * @return {module:model/Degree} The populated <code>Degree</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Degree();

            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], 'String');
            }
            if (data.hasOwnProperty('domain')) {
                obj['domain'] = ApiClient.convertToType(data['domain'], 'String');
            }
            if (data.hasOwnProperty('institution')) {
                obj['institution'] = ApiClient.convertToType(data['institution'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Degree level
 * @member {String} level
 */
Degree.prototype['level'] = undefined;

/**
 * Degree domain
 * @member {String} domain
 */
Degree.prototype['domain'] = undefined;

/**
 * Degree institution
 * @member {String} institution
 */
Degree.prototype['institution'] = undefined;






export default Degree;

