/**
 * Tournesol API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import StatusEnum from './StatusEnum';

/**
 * The EmailDomain model module.
 * @module model/EmailDomain
 * @version 2.0.0
 */
class EmailDomain {
    /**
     * Constructs a new <code>EmailDomain</code>.
     * E-mail domain
     * @alias module:model/EmailDomain
     * @param domain {String} E-mail domain with leading @
     * @param nVerifiedEmails {Number} Number of verified emails with ths domain
     */
    constructor(domain, nVerifiedEmails) { 
        
        EmailDomain.initialize(this, domain, nVerifiedEmails);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, domain, nVerifiedEmails) { 
        obj['domain'] = domain;
        obj['n_verified_emails'] = nVerifiedEmails;
    }

    /**
     * Constructs a <code>EmailDomain</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EmailDomain} obj Optional instance to populate.
     * @return {module:model/EmailDomain} The populated <code>EmailDomain</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmailDomain();

            if (data.hasOwnProperty('domain')) {
                obj['domain'] = ApiClient.convertToType(data['domain'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], StatusEnum);
            }
            if (data.hasOwnProperty('n_verified_emails')) {
                obj['n_verified_emails'] = ApiClient.convertToType(data['n_verified_emails'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * E-mail domain with leading @
 * @member {String} domain
 */
EmailDomain.prototype['domain'] = undefined;

/**
 * Status of the domain.
 * @member {module:model/StatusEnum} status
 */
EmailDomain.prototype['status'] = undefined;

/**
 * Number of verified emails with ths domain
 * @member {Number} n_verified_emails
 */
EmailDomain.prototype['n_verified_emails'] = undefined;






export default EmailDomain;

