/**
 * Tournesol API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Expertise model module.
 * @module model/Expertise
 * @version 2.0.0
 */
class Expertise {
    /**
     * Constructs a new <code>Expertise</code>.
     * Expertise
     * @alias module:model/Expertise
     * @param name {String} Expertise description
     */
    constructor(name) { 
        
        Expertise.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>Expertise</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Expertise} obj Optional instance to populate.
     * @return {module:model/Expertise} The populated <code>Expertise</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Expertise();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Expertise description
 * @member {String} name
 */
Expertise.prototype['name'] = undefined;






export default Expertise;

