/**
 * Tournesol API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ExpertiseKeyword model module.
 * @module model/ExpertiseKeyword
 * @version 2.0.0
 */
class ExpertiseKeyword {
    /**
     * Constructs a new <code>ExpertiseKeyword</code>.
     * Expertise keyword
     * @alias module:model/ExpertiseKeyword
     * @param name {String} Expertise keyword description
     */
    constructor(name) { 
        
        ExpertiseKeyword.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>ExpertiseKeyword</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExpertiseKeyword} obj Optional instance to populate.
     * @return {module:model/ExpertiseKeyword} The populated <code>ExpertiseKeyword</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExpertiseKeyword();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Expertise keyword description
 * @member {String} name
 */
ExpertiseKeyword.prototype['name'] = undefined;






export default ExpertiseKeyword;

