/**
 * Tournesol API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class GenderEnum.
* @enum {}
* @readonly
*/
export default class GenderEnum {
    
        /**
         * value: "Not Specified"
         * @const
         */
        "Not Specified" = "Not Specified";

    
        /**
         * value: "Non-binary"
         * @const
         */
        "Non-binary" = "Non-binary";

    
        /**
         * value: "Other"
         * @const
         */
        "Other" = "Other";

    
        /**
         * value: "Female"
         * @const
         */
        "Female" = "Female";

    
        /**
         * value: "Male"
         * @const
         */
        "Male" = "Male";

    

    /**
    * Returns a <code>GenderEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/GenderEnum} The enum <code>GenderEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

