/**
 * Tournesol API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class GenericErrorDetailEnum.
* @enum {}
* @readonly
*/
export default class GenericErrorDetailEnum {
    
        /**
         * value: "UNKNOWN"
         * @const
         */
        "UNKNOWN" = "UNKNOWN";

    
        /**
         * value: "DB_ERROR"
         * @const
         */
        "DB_ERROR" = "DB_ERROR";

    
        /**
         * value: "PK_ERROR"
         * @const
         */
        "PK_ERROR" = "PK_ERROR";

    
        /**
         * value: "NO_VIDEOS"
         * @const
         */
        "NO_VIDEOS" = "NO_VIDEOS";

    
        /**
         * value: "ALREADY_EXISTS"
         * @const
         */
        "ALREADY_EXISTS" = "ALREADY_EXISTS";

    

    /**
    * Returns a <code>GenericErrorDetailEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/GenericErrorDetailEnum} The enum <code>GenericErrorDetailEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

