/**
 * Tournesol API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NumberOfThanks model module.
 * @module model/NumberOfThanks
 * @version 2.0.0
 */
class NumberOfThanks {
    /**
     * Constructs a new <code>NumberOfThanks</code>.
     * @alias module:model/NumberOfThanks
     * @param nThanks {Number} Number of people I thanked for this video
     */
    constructor(nThanks) { 
        
        NumberOfThanks.initialize(this, nThanks);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, nThanks) { 
        obj['n_thanks'] = nThanks;
    }

    /**
     * Constructs a <code>NumberOfThanks</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NumberOfThanks} obj Optional instance to populate.
     * @return {module:model/NumberOfThanks} The populated <code>NumberOfThanks</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NumberOfThanks();

            if (data.hasOwnProperty('n_thanks')) {
                obj['n_thanks'] = ApiClient.convertToType(data['n_thanks'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Number of people I thanked for this video
 * @member {Number} n_thanks
 */
NumberOfThanks.prototype['n_thanks'] = undefined;






export default NumberOfThanks;

