/**
 * Tournesol API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VideoCommentsSerializerV2 from './VideoCommentsSerializerV2';

/**
 * The PaginatedVideoCommentsSerializerV2List model module.
 * @module model/PaginatedVideoCommentsSerializerV2List
 * @version 2.0.0
 */
class PaginatedVideoCommentsSerializerV2List {
    /**
     * Constructs a new <code>PaginatedVideoCommentsSerializerV2List</code>.
     * @alias module:model/PaginatedVideoCommentsSerializerV2List
     */
    constructor() { 
        
        PaginatedVideoCommentsSerializerV2List.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaginatedVideoCommentsSerializerV2List</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaginatedVideoCommentsSerializerV2List} obj Optional instance to populate.
     * @return {module:model/PaginatedVideoCommentsSerializerV2List} The populated <code>PaginatedVideoCommentsSerializerV2List</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaginatedVideoCommentsSerializerV2List();

            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('next')) {
                obj['next'] = ApiClient.convertToType(data['next'], 'String');
            }
            if (data.hasOwnProperty('previous')) {
                obj['previous'] = ApiClient.convertToType(data['previous'], 'String');
            }
            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [VideoCommentsSerializerV2]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} count
 */
PaginatedVideoCommentsSerializerV2List.prototype['count'] = undefined;

/**
 * @member {String} next
 */
PaginatedVideoCommentsSerializerV2List.prototype['next'] = undefined;

/**
 * @member {String} previous
 */
PaginatedVideoCommentsSerializerV2List.prototype['previous'] = undefined;

/**
 * @member {Array.<module:model/VideoCommentsSerializerV2>} results
 */
PaginatedVideoCommentsSerializerV2List.prototype['results'] = undefined;






export default PaginatedVideoCommentsSerializerV2List;

