/**
 * Tournesol API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PatchedDegree model module.
 * @module model/PatchedDegree
 * @version 2.0.0
 */
class PatchedDegree {
    /**
     * Constructs a new <code>PatchedDegree</code>.
     * Degree
     * @alias module:model/PatchedDegree
     */
    constructor() { 
        
        PatchedDegree.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PatchedDegree</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PatchedDegree} obj Optional instance to populate.
     * @return {module:model/PatchedDegree} The populated <code>PatchedDegree</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PatchedDegree();

            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], 'String');
            }
            if (data.hasOwnProperty('domain')) {
                obj['domain'] = ApiClient.convertToType(data['domain'], 'String');
            }
            if (data.hasOwnProperty('institution')) {
                obj['institution'] = ApiClient.convertToType(data['institution'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Degree level
 * @member {String} level
 */
PatchedDegree.prototype['level'] = undefined;

/**
 * Degree domain
 * @member {String} domain
 */
PatchedDegree.prototype['domain'] = undefined;

/**
 * Degree institution
 * @member {String} institution
 */
PatchedDegree.prototype['institution'] = undefined;






export default PatchedDegree;

