/**
 * Tournesol API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PatchedExpertRatingsSerializerV2 model module.
 * @module model/PatchedExpertRatingsSerializerV2
 * @version 2.0.0
 */
class PatchedExpertRatingsSerializerV2 {
    /**
     * Constructs a new <code>PatchedExpertRatingsSerializerV2</code>.
     * Serialize ExpertRatings.
     * @alias module:model/PatchedExpertRatingsSerializerV2
     */
    constructor() { 
        
        PatchedExpertRatingsSerializerV2.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PatchedExpertRatingsSerializerV2</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PatchedExpertRatingsSerializerV2} obj Optional instance to populate.
     * @return {module:model/PatchedExpertRatingsSerializerV2} The populated <code>PatchedExpertRatingsSerializerV2</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PatchedExpertRatingsSerializerV2();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('video_1')) {
                obj['video_1'] = ApiClient.convertToType(data['video_1'], 'String');
            }
            if (data.hasOwnProperty('video_2')) {
                obj['video_2'] = ApiClient.convertToType(data['video_2'], 'String');
            }
            if (data.hasOwnProperty('duration_ms')) {
                obj['duration_ms'] = ApiClient.convertToType(data['duration_ms'], 'Number');
            }
            if (data.hasOwnProperty('largely_recommended')) {
                obj['largely_recommended'] = ApiClient.convertToType(data['largely_recommended'], 'Number');
            }
            if (data.hasOwnProperty('reliability')) {
                obj['reliability'] = ApiClient.convertToType(data['reliability'], 'Number');
            }
            if (data.hasOwnProperty('importance')) {
                obj['importance'] = ApiClient.convertToType(data['importance'], 'Number');
            }
            if (data.hasOwnProperty('engaging')) {
                obj['engaging'] = ApiClient.convertToType(data['engaging'], 'Number');
            }
            if (data.hasOwnProperty('pedagogy')) {
                obj['pedagogy'] = ApiClient.convertToType(data['pedagogy'], 'Number');
            }
            if (data.hasOwnProperty('layman_friendly')) {
                obj['layman_friendly'] = ApiClient.convertToType(data['layman_friendly'], 'Number');
            }
            if (data.hasOwnProperty('diversity_inclusion')) {
                obj['diversity_inclusion'] = ApiClient.convertToType(data['diversity_inclusion'], 'Number');
            }
            if (data.hasOwnProperty('backfire_risk')) {
                obj['backfire_risk'] = ApiClient.convertToType(data['backfire_risk'], 'Number');
            }
            if (data.hasOwnProperty('better_habits')) {
                obj['better_habits'] = ApiClient.convertToType(data['better_habits'], 'Number');
            }
            if (data.hasOwnProperty('entertaining_relaxing')) {
                obj['entertaining_relaxing'] = ApiClient.convertToType(data['entertaining_relaxing'], 'Number');
            }
            if (data.hasOwnProperty('largely_recommended_weight')) {
                obj['largely_recommended_weight'] = ApiClient.convertToType(data['largely_recommended_weight'], 'Number');
            }
            if (data.hasOwnProperty('reliability_weight')) {
                obj['reliability_weight'] = ApiClient.convertToType(data['reliability_weight'], 'Number');
            }
            if (data.hasOwnProperty('importance_weight')) {
                obj['importance_weight'] = ApiClient.convertToType(data['importance_weight'], 'Number');
            }
            if (data.hasOwnProperty('engaging_weight')) {
                obj['engaging_weight'] = ApiClient.convertToType(data['engaging_weight'], 'Number');
            }
            if (data.hasOwnProperty('pedagogy_weight')) {
                obj['pedagogy_weight'] = ApiClient.convertToType(data['pedagogy_weight'], 'Number');
            }
            if (data.hasOwnProperty('layman_friendly_weight')) {
                obj['layman_friendly_weight'] = ApiClient.convertToType(data['layman_friendly_weight'], 'Number');
            }
            if (data.hasOwnProperty('diversity_inclusion_weight')) {
                obj['diversity_inclusion_weight'] = ApiClient.convertToType(data['diversity_inclusion_weight'], 'Number');
            }
            if (data.hasOwnProperty('backfire_risk_weight')) {
                obj['backfire_risk_weight'] = ApiClient.convertToType(data['backfire_risk_weight'], 'Number');
            }
            if (data.hasOwnProperty('better_habits_weight')) {
                obj['better_habits_weight'] = ApiClient.convertToType(data['better_habits_weight'], 'Number');
            }
            if (data.hasOwnProperty('entertaining_relaxing_weight')) {
                obj['entertaining_relaxing_weight'] = ApiClient.convertToType(data['entertaining_relaxing_weight'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
PatchedExpertRatingsSerializerV2.prototype['id'] = undefined;

/**
 * Username of this user
 * @member {String} username
 */
PatchedExpertRatingsSerializerV2.prototype['username'] = undefined;

/**
 * @member {String} video_1
 */
PatchedExpertRatingsSerializerV2.prototype['video_1'] = undefined;

/**
 * @member {String} video_2
 */
PatchedExpertRatingsSerializerV2.prototype['video_2'] = undefined;

/**
 * Time it took to rate the videos (in milliseconds)
 * @member {Number} duration_ms
 */
PatchedExpertRatingsSerializerV2.prototype['duration_ms'] = undefined;

/**
 * Should be largely recommended
 * @member {Number} largely_recommended
 */
PatchedExpertRatingsSerializerV2.prototype['largely_recommended'] = undefined;

/**
 * Reliable and not misleading
 * @member {Number} reliability
 */
PatchedExpertRatingsSerializerV2.prototype['reliability'] = undefined;

/**
 * Important and actionable
 * @member {Number} importance
 */
PatchedExpertRatingsSerializerV2.prototype['importance'] = undefined;

/**
 * Engaging and thought-provoking
 * @member {Number} engaging
 */
PatchedExpertRatingsSerializerV2.prototype['engaging'] = undefined;

/**
 * Clear and pedagogical
 * @member {Number} pedagogy
 */
PatchedExpertRatingsSerializerV2.prototype['pedagogy'] = undefined;

/**
 * Layman-friendly
 * @member {Number} layman_friendly
 */
PatchedExpertRatingsSerializerV2.prototype['layman_friendly'] = undefined;

/**
 * Diversity and Inclusion
 * @member {Number} diversity_inclusion
 */
PatchedExpertRatingsSerializerV2.prototype['diversity_inclusion'] = undefined;

/**
 * Resilience to backfiring risks
 * @member {Number} backfire_risk
 */
PatchedExpertRatingsSerializerV2.prototype['backfire_risk'] = undefined;

/**
 * Encourages better habits
 * @member {Number} better_habits
 */
PatchedExpertRatingsSerializerV2.prototype['better_habits'] = undefined;

/**
 * Entertaining and relaxing
 * @member {Number} entertaining_relaxing
 */
PatchedExpertRatingsSerializerV2.prototype['entertaining_relaxing'] = undefined;

/**
 * Should be largely recommended weight
 * @member {Number} largely_recommended_weight
 */
PatchedExpertRatingsSerializerV2.prototype['largely_recommended_weight'] = undefined;

/**
 * Reliable and not misleading weight
 * @member {Number} reliability_weight
 */
PatchedExpertRatingsSerializerV2.prototype['reliability_weight'] = undefined;

/**
 * Important and actionable weight
 * @member {Number} importance_weight
 */
PatchedExpertRatingsSerializerV2.prototype['importance_weight'] = undefined;

/**
 * Engaging and thought-provoking weight
 * @member {Number} engaging_weight
 */
PatchedExpertRatingsSerializerV2.prototype['engaging_weight'] = undefined;

/**
 * Clear and pedagogical weight
 * @member {Number} pedagogy_weight
 */
PatchedExpertRatingsSerializerV2.prototype['pedagogy_weight'] = undefined;

/**
 * Layman-friendly weight
 * @member {Number} layman_friendly_weight
 */
PatchedExpertRatingsSerializerV2.prototype['layman_friendly_weight'] = undefined;

/**
 * Diversity and Inclusion weight
 * @member {Number} diversity_inclusion_weight
 */
PatchedExpertRatingsSerializerV2.prototype['diversity_inclusion_weight'] = undefined;

/**
 * Resilience to backfiring risks weight
 * @member {Number} backfire_risk_weight
 */
PatchedExpertRatingsSerializerV2.prototype['backfire_risk_weight'] = undefined;

/**
 * Encourages better habits weight
 * @member {Number} better_habits_weight
 */
PatchedExpertRatingsSerializerV2.prototype['better_habits_weight'] = undefined;

/**
 * Entertaining and relaxing weight
 * @member {Number} entertaining_relaxing_weight
 */
PatchedExpertRatingsSerializerV2.prototype['entertaining_relaxing_weight'] = undefined;






export default PatchedExpertRatingsSerializerV2;

