/**
 * Tournesol API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class RatingModeEnum.
* @enum {}
* @readonly
*/
export default class RatingModeEnum {
    
        /**
         * value: "enable_all"
         * @const
         */
        "enable_all" = "enable_all";

    
        /**
         * value: "skip"
         * @const
         */
        "skip" = "skip";

    
        /**
         * value: "confidence"
         * @const
         */
        "confidence" = "confidence";

    

    /**
    * Returns a <code>RatingModeEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/RatingModeEnum} The enum <code>RatingModeEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

