/**
 * Tournesol API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ContextEnum from './ContextEnum';

/**
 * The SliderChangeSerializerV2 model module.
 * @module model/SliderChangeSerializerV2
 * @version 2.0.0
 */
class SliderChangeSerializerV2 {
    /**
     * Constructs a new <code>SliderChangeSerializerV2</code>.
     * Serialize ExpertRating slider changes.
     * @alias module:model/SliderChangeSerializerV2
     * @param id {Number} 
     * @param username {String} Username of this user
     * @param videoLeft {String} 
     * @param videoRight {String} 
     */
    constructor(id, username, videoLeft, videoRight) { 
        
        SliderChangeSerializerV2.initialize(this, id, username, videoLeft, videoRight);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, username, videoLeft, videoRight) { 
        obj['id'] = id;
        obj['username'] = username;
        obj['video_left'] = videoLeft;
        obj['video_right'] = videoRight;
    }

    /**
     * Constructs a <code>SliderChangeSerializerV2</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SliderChangeSerializerV2} obj Optional instance to populate.
     * @return {module:model/SliderChangeSerializerV2} The populated <code>SliderChangeSerializerV2</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SliderChangeSerializerV2();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('video_left')) {
                obj['video_left'] = ApiClient.convertToType(data['video_left'], 'String');
            }
            if (data.hasOwnProperty('video_right')) {
                obj['video_right'] = ApiClient.convertToType(data['video_right'], 'String');
            }
            if (data.hasOwnProperty('duration_ms')) {
                obj['duration_ms'] = ApiClient.convertToType(data['duration_ms'], 'Number');
            }
            if (data.hasOwnProperty('context')) {
                obj['context'] = ApiClient.convertToType(data['context'], ContextEnum);
            }
            if (data.hasOwnProperty('largely_recommended')) {
                obj['largely_recommended'] = ApiClient.convertToType(data['largely_recommended'], 'Number');
            }
            if (data.hasOwnProperty('reliability')) {
                obj['reliability'] = ApiClient.convertToType(data['reliability'], 'Number');
            }
            if (data.hasOwnProperty('importance')) {
                obj['importance'] = ApiClient.convertToType(data['importance'], 'Number');
            }
            if (data.hasOwnProperty('engaging')) {
                obj['engaging'] = ApiClient.convertToType(data['engaging'], 'Number');
            }
            if (data.hasOwnProperty('pedagogy')) {
                obj['pedagogy'] = ApiClient.convertToType(data['pedagogy'], 'Number');
            }
            if (data.hasOwnProperty('layman_friendly')) {
                obj['layman_friendly'] = ApiClient.convertToType(data['layman_friendly'], 'Number');
            }
            if (data.hasOwnProperty('diversity_inclusion')) {
                obj['diversity_inclusion'] = ApiClient.convertToType(data['diversity_inclusion'], 'Number');
            }
            if (data.hasOwnProperty('backfire_risk')) {
                obj['backfire_risk'] = ApiClient.convertToType(data['backfire_risk'], 'Number');
            }
            if (data.hasOwnProperty('better_habits')) {
                obj['better_habits'] = ApiClient.convertToType(data['better_habits'], 'Number');
            }
            if (data.hasOwnProperty('entertaining_relaxing')) {
                obj['entertaining_relaxing'] = ApiClient.convertToType(data['entertaining_relaxing'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
SliderChangeSerializerV2.prototype['id'] = undefined;

/**
 * Username of this user
 * @member {String} username
 */
SliderChangeSerializerV2.prototype['username'] = undefined;

/**
 * @member {String} video_left
 */
SliderChangeSerializerV2.prototype['video_left'] = undefined;

/**
 * @member {String} video_right
 */
SliderChangeSerializerV2.prototype['video_right'] = undefined;

/**
 * Time from page load to this slider value (in milliseconds)
 * @member {Number} duration_ms
 */
SliderChangeSerializerV2.prototype['duration_ms'] = undefined;

/**
 * The page where slider change occurs
 * @member {module:model/ContextEnum} context
 */
SliderChangeSerializerV2.prototype['context'] = undefined;

/**
 * Should be largely recommended
 * @member {Number} largely_recommended
 */
SliderChangeSerializerV2.prototype['largely_recommended'] = undefined;

/**
 * Reliable and not misleading
 * @member {Number} reliability
 */
SliderChangeSerializerV2.prototype['reliability'] = undefined;

/**
 * Important and actionable
 * @member {Number} importance
 */
SliderChangeSerializerV2.prototype['importance'] = undefined;

/**
 * Engaging and thought-provoking
 * @member {Number} engaging
 */
SliderChangeSerializerV2.prototype['engaging'] = undefined;

/**
 * Clear and pedagogical
 * @member {Number} pedagogy
 */
SliderChangeSerializerV2.prototype['pedagogy'] = undefined;

/**
 * Layman-friendly
 * @member {Number} layman_friendly
 */
SliderChangeSerializerV2.prototype['layman_friendly'] = undefined;

/**
 * Diversity and Inclusion
 * @member {Number} diversity_inclusion
 */
SliderChangeSerializerV2.prototype['diversity_inclusion'] = undefined;

/**
 * Resilience to backfiring risks
 * @member {Number} backfire_risk
 */
SliderChangeSerializerV2.prototype['backfire_risk'] = undefined;

/**
 * Encourages better habits
 * @member {Number} better_habits
 */
SliderChangeSerializerV2.prototype['better_habits'] = undefined;

/**
 * Entertaining and relaxing
 * @member {Number} entertaining_relaxing
 */
SliderChangeSerializerV2.prototype['entertaining_relaxing'] = undefined;






export default SliderChangeSerializerV2;

