/**
 * Tournesol API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StatisticsSerializerV2 model module.
 * @module model/StatisticsSerializerV2
 * @version 2.0.0
 */
class StatisticsSerializerV2 {
    /**
     * Constructs a new <code>StatisticsSerializerV2</code>.
     * Serialize statistics for the website.
     * @alias module:model/StatisticsSerializerV2
     * @param certifiedExperts {Number} Number of experts with certified e-mails
     * @param pairwiseComparisons {Number} Total number of pairwise comparisons
     * @param videos {Number} Total number of videos in the database
     * @param minScore {Number} Minimal aggregated score over all videos and features
     * @param maxScore {Number} Maximal aggregated score over all videos and features
     */
    constructor(certifiedExperts, pairwiseComparisons, videos, minScore, maxScore) { 
        
        StatisticsSerializerV2.initialize(this, certifiedExperts, pairwiseComparisons, videos, minScore, maxScore);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, certifiedExperts, pairwiseComparisons, videos, minScore, maxScore) { 
        obj['certified_experts'] = certifiedExperts;
        obj['pairwise_comparisons'] = pairwiseComparisons;
        obj['videos'] = videos;
        obj['min_score'] = minScore;
        obj['max_score'] = maxScore;
    }

    /**
     * Constructs a <code>StatisticsSerializerV2</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StatisticsSerializerV2} obj Optional instance to populate.
     * @return {module:model/StatisticsSerializerV2} The populated <code>StatisticsSerializerV2</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StatisticsSerializerV2();

            if (data.hasOwnProperty('certified_experts')) {
                obj['certified_experts'] = ApiClient.convertToType(data['certified_experts'], 'Number');
            }
            if (data.hasOwnProperty('pairwise_comparisons')) {
                obj['pairwise_comparisons'] = ApiClient.convertToType(data['pairwise_comparisons'], 'Number');
            }
            if (data.hasOwnProperty('videos')) {
                obj['videos'] = ApiClient.convertToType(data['videos'], 'Number');
            }
            if (data.hasOwnProperty('min_score')) {
                obj['min_score'] = ApiClient.convertToType(data['min_score'], 'Number');
            }
            if (data.hasOwnProperty('max_score')) {
                obj['max_score'] = ApiClient.convertToType(data['max_score'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Number of experts with certified e-mails
 * @member {Number} certified_experts
 */
StatisticsSerializerV2.prototype['certified_experts'] = undefined;

/**
 * Total number of pairwise comparisons
 * @member {Number} pairwise_comparisons
 */
StatisticsSerializerV2.prototype['pairwise_comparisons'] = undefined;

/**
 * Total number of videos in the database
 * @member {Number} videos
 */
StatisticsSerializerV2.prototype['videos'] = undefined;

/**
 * Minimal aggregated score over all videos and features
 * @member {Number} min_score
 */
StatisticsSerializerV2.prototype['min_score'] = undefined;

/**
 * Maximal aggregated score over all videos and features
 * @member {Number} max_score
 */
StatisticsSerializerV2.prototype['max_score'] = undefined;






export default StatisticsSerializerV2;

