/**
 * Tournesol API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VerifiableEmail model module.
 * @module model/VerifiableEmail
 * @version 2.0.0
 */
class VerifiableEmail {
    /**
     * Constructs a new <code>VerifiableEmail</code>.
     * E-mail
     * @alias module:model/VerifiableEmail
     * @param email {String} E-mail address
     * @param isVerified {Boolean} Verified
     */
    constructor(email, isVerified) { 
        
        VerifiableEmail.initialize(this, email, isVerified);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, isVerified) { 
        obj['email'] = email;
        obj['is_verified'] = isVerified;
    }

    /**
     * Constructs a <code>VerifiableEmail</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VerifiableEmail} obj Optional instance to populate.
     * @return {module:model/VerifiableEmail} The populated <code>VerifiableEmail</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VerifiableEmail();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('is_verified')) {
                obj['is_verified'] = ApiClient.convertToType(data['is_verified'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * E-mail address
 * @member {String} email
 */
VerifiableEmail.prototype['email'] = undefined;

/**
 * Verified
 * @member {Boolean} is_verified
 */
VerifiableEmail.prototype['is_verified'] = undefined;






export default VerifiableEmail;

