/**
 * Tournesol API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VideoSerializerV2 from './VideoSerializerV2';

/**
 * The VideoRateLaterSerializerV2 model module.
 * @module model/VideoRateLaterSerializerV2
 * @version 2.0.0
 */
class VideoRateLaterSerializerV2 {
    /**
     * Constructs a new <code>VideoRateLaterSerializerV2</code>.
     * Serialize rate later objects.
     * @alias module:model/VideoRateLaterSerializerV2
     * @param id {Number} ID of the video rate later object
     * @param video {String} Youtube Video ID
     * @param username {String} User username
     * @param datetimeAdd {Date} When video was added
     * @param videoInfo {module:model/VideoSerializerV2} 
     */
    constructor(id, video, username, datetimeAdd, videoInfo) { 
        
        VideoRateLaterSerializerV2.initialize(this, id, video, username, datetimeAdd, videoInfo);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, video, username, datetimeAdd, videoInfo) { 
        obj['id'] = id;
        obj['video'] = video;
        obj['username'] = username;
        obj['datetime_add'] = datetimeAdd;
        obj['video_info'] = videoInfo;
    }

    /**
     * Constructs a <code>VideoRateLaterSerializerV2</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VideoRateLaterSerializerV2} obj Optional instance to populate.
     * @return {module:model/VideoRateLaterSerializerV2} The populated <code>VideoRateLaterSerializerV2</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VideoRateLaterSerializerV2();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('video')) {
                obj['video'] = ApiClient.convertToType(data['video'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('datetime_add')) {
                obj['datetime_add'] = ApiClient.convertToType(data['datetime_add'], 'Date');
            }
            if (data.hasOwnProperty('video_info')) {
                obj['video_info'] = ApiClient.convertToType(data['video_info'], VideoSerializerV2);
            }
        }
        return obj;
    }


}

/**
 * ID of the video rate later object
 * @member {Number} id
 */
VideoRateLaterSerializerV2.prototype['id'] = undefined;

/**
 * Youtube Video ID
 * @member {String} video
 */
VideoRateLaterSerializerV2.prototype['video'] = undefined;

/**
 * User username
 * @member {String} username
 */
VideoRateLaterSerializerV2.prototype['username'] = undefined;

/**
 * When video was added
 * @member {Date} datetime_add
 */
VideoRateLaterSerializerV2.prototype['datetime_add'] = undefined;

/**
 * @member {module:model/VideoSerializerV2} video_info
 */
VideoRateLaterSerializerV2.prototype['video_info'] = undefined;






export default VideoRateLaterSerializerV2;

