# Generated by Django 3.0.6 on 2020-05-11 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('accuracy', models.FloatField()),
                ('pedagogy', models.FloatField()),
                ('importance', models.FloatField()),
                ('entertainment', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('caption_text', models.TextField()),
                ('embedding', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='ExpertRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField()),
                ('pedagogy', models.FloatField()),
                ('importance', models.FloatField()),
                ('entertainment', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
                ('video_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertrating_video_1', to='backend.Video')),
                ('video_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertrating_video_2', to='backend.Video')),
            ],
        ),
    ]
