# Generated by Django 3.0.6 on 2020-05-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200511_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserPreferences'),
        ),
    ]
