# Generated by Django 3.0.6 on 2020-05-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200511_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='entertainment',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='importance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='pedagogy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='caption_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='embedding',
            field=models.BinaryField(null=True),
        ),
    ]
