# Generated by Django 3.0.6 on 2020-05-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200511_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
