# Generated by Django 3.0.6 on 2020-05-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_userpreferences_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertrating',
            name='backfire_risk',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='backfire_risk',
            field=models.FloatField(default=0),
        ),
    ]
