# Generated by Django 3.0.6 on 2020-06-02 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200528_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertrating',
            old_name='entertainment',
            new_name='engaging',
        ),
        migrations.RenameField(
            model_name='userpreferences',
            old_name='entertainment',
            new_name='engaging',
        ),
    ]
