# Generated by Django 3.0.6 on 2020-06-02 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200602_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertrating',
            old_name='accuracy',
            new_name='reliability',
        ),
        migrations.RenameField(
            model_name='userpreferences',
            old_name='accuracy',
            new_name='reliability',
        ),
    ]
