# Generated by Django 3.0.7 on 2020-06-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200602_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='info',
            field=models.TextField(null=True),
        ),
    ]
