# Generated by Django 3.0.7 on 2020-06-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_video_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertrating',
            name='duration_ms',
            field=models.FloatField(default=0, null=True),
        ),
    ]
