# Generated by Django 3.0.7 on 2020-06-25 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20200618_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField(null=True)),
                ('troll', models.BooleanField(default=False, help_text='The content is a troll', null=True)),
                ('kid', models.BooleanField(default=False, help_text='The content is not kid-friendly', null=True)),
                ('misl0', models.BooleanField(default=False, help_text='The content is slightly misleading', null=True)),
                ('misl1', models.BooleanField(default=False, help_text='The content is very misleading', null=True)),
                ('misl2', models.BooleanField(default=False, help_text='The misinformation of the content is misleading and dangerous', null=True)),
                ('hate', models.BooleanField(default=False, help_text='The content contains hate speech', null=True)),
                ('violence', models.BooleanField(default=False, help_text='The content promotes violence', null=True)),
                ('bully', models.BooleanField(default=False, help_text='The content is cyber-bullying', null=True)),
                ('threat', models.BooleanField(default=False, help_text='The content contains threats', null=True)),
                ('violent_act', models.BooleanField(default=False, help_text='The content calls for violent acts', null=True)),
                ('death_threat', models.BooleanField(default=False, help_text='The content contains death threats', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserPreferences')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Video')),
            ],
        ),
    ]
