# Generated by Django 3.0.7 on 2020-06-25 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_videoreports'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videoreports',
            unique_together={('user', 'video')},
        ),
    ]
