# Generated by Django 3.0.7 on 2020-06-26 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20200626_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videocomment_parent_comment', to='backend.VideoComment'),
        ),
    ]
