# Generated by Django 3.0.7 on 2020-06-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20200625_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertrating',
            name='backfire_risk',
            field=models.FloatField(help_text='Resilience to backfiring risks'),
        ),
        migrations.AlterField(
            model_name='expertrating',
            name='engaging',
            field=models.FloatField(help_text='Engaging'),
        ),
        migrations.AlterField(
            model_name='expertrating',
            name='importance',
            field=models.FloatField(help_text='Importance'),
        ),
        migrations.AlterField(
            model_name='expertrating',
            name='pedagogy',
            field=models.FloatField(help_text='Pedagogy'),
        ),
        migrations.AlterField(
            model_name='expertrating',
            name='reliability',
            field=models.FloatField(help_text='Reliability'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='backfire_risk',
            field=models.FloatField(default=0, help_text='Resilience to backfiring risks'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='engaging',
            field=models.FloatField(default=0, help_text='Engaging'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='importance',
            field=models.FloatField(default=0, help_text='Importance'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='pedagogy',
            field=models.FloatField(default=0, help_text='Pedagogy'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='reliability',
            field=models.FloatField(default=0, help_text='Reliability'),
        ),
    ]
