# Generated by Django 3.0.7 on 2020-06-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20200625_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoreports',
            name='explanation',
            field=models.TextField(default='', null=True),
        ),
    ]
