# Generated by Django 3.0.7 on 2020-06-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20200626_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocomment',
            name='red_flags',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='votes_minus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='votes_plus',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
