# Generated by Django 3.0.7 on 2020-07-01 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20200627_0008'),
        ('backend', '0016_auto_20200625_2234'),
    ]

    operations = [
    ]
