# Generated by Django 3.0.7 on 2020-07-06 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_merge_20200701_2305'),
        ('backend', '0019_merge_20200702_1059'),
    ]

    operations = [
    ]
