# Generated by Django 3.0.7 on 2020-07-06 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_merge_20200706_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videocomment_parent_comment', to='backend.VideoComment'),
        ),
    ]
