# Generated by Django 3.0.7 on 2020-07-06 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20200706_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCommentMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('which', models.CharField(choices=[('vote_plus', 'votes_plus'), ('vote_minus', 'votes_minus'), ('red_flag', 'red_flags')], max_length=15)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videocommentmarker_comment', to='backend.VideoComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videocommentmarker_user', to='backend.UserPreferences')),
            ],
            options={
                'unique_together': {('user', 'comment', 'which')},
            },
        ),
        migrations.DeleteModel(
            name='VideoCommentMarkers',
        ),
    ]
