# Generated by Django 3.0.7 on 2020-07-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20200706_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocomment',
            name='backfire_risk',
            field=models.BooleanField(default=False, help_text='Resilience to backfiring risks', null=True),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='engaging',
            field=models.BooleanField(default=False, help_text='Engaging', null=True),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='importance',
            field=models.BooleanField(default=False, help_text='Importance', null=True),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='pedagogy',
            field=models.BooleanField(default=False, help_text='Pedagogy', null=True),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='reliability',
            field=models.BooleanField(default=False, help_text='Reliability', null=True),
        ),
    ]
