# Generated by Django 3.0.7 on 2020-07-28 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20200716_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reliability', models.FloatField(default=0, help_text='Reliability')),
                ('pedagogy', models.FloatField(default=0, help_text='Pedagogy')),
                ('importance', models.FloatField(default=0, help_text='Importance')),
                ('engaging', models.FloatField(default=0, help_text='Engaging')),
                ('backfire_risk', models.FloatField(default=0, help_text='Resilience to backfiring risks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserPreferences')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Video')),
            ],
            options={
                'unique_together': {('user', 'video')},
            },
        ),
    ]
