# Generated by Django 3.0.7 on 2020-08-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_videorating'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertrating',
            name='backfire_risk_weight',
            field=models.FloatField(default=1, help_text='Resilience to backfiring risks weight'),
        ),
        migrations.AddField(
            model_name='expertrating',
            name='engaging_weight',
            field=models.FloatField(default=1, help_text='Engaging weight'),
        ),
        migrations.AddField(
            model_name='expertrating',
            name='importance_weight',
            field=models.FloatField(default=1, help_text='Importance weight'),
        ),
        migrations.AddField(
            model_name='expertrating',
            name='pedagogy_weight',
            field=models.FloatField(default=1, help_text='Pedagogy weight'),
        ),
        migrations.AddField(
            model_name='expertrating',
            name='reliability_weight',
            field=models.FloatField(default=1, help_text='Reliability weight'),
        ),
    ]
