# Generated by Django 3.0.7 on 2020-11-25 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_auto_20201125_0804'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expertrating',
            unique_together={('user', 'video_1_2_ids_sorted')},
        ),
    ]
