# Generated by Django 3.0.7 on 2020-12-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_auto_20201201_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='description',
            field=models.TextField(help_text='Self-description of the expert (degree, biography, ...)', null=True),
        ),
    ]
