# Generated by Django 3.0.7 on 2020-12-03 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_auto_20201201_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='backfire_risk',
            field=models.FloatField(default=0, help_text='Resilience to backfiring risks', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='engaging',
            field=models.FloatField(default=0, help_text='Engaging', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='importance',
            field=models.FloatField(default=0, help_text='Importance', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='pedagogy',
            field=models.FloatField(default=0, help_text='Pedagogy', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='reliability',
            field=models.FloatField(default=0, help_text='Reliability', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
