# Generated by Django 3.0.7 on 2020-12-12 18:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0034_auto_20201203_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='description',
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Your position', null=True)),
                ('bio', models.TextField(help_text='Self-description (degree, biography, ...)', null=True)),
                ('comment_anonymously', models.BooleanField(default=False, help_text='Comment anonymously by-default')),
                ('show_online_presence', models.BooleanField(default=False, help_text='Show my online presence on Tournesol')),
                ('birth_year', models.IntegerField(help_text='Year of birth', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('gender', models.CharField(help_text='Your gender', max_length=50, null=True)),
                ('nationality', models.CharField(help_text='Your nationality', max_length=50, null=True)),
                ('race', models.CharField(help_text='Your race', max_length=50, null=True)),
                ('political_affiliation', models.CharField(help_text='Your political affiliation', max_length=50, null=True)),
                ('religion', models.CharField(help_text='Your religion', max_length=50, null=True)),
                ('degree_of_political_engagement', models.CharField(help_text='Your degree of political engagement', max_length=50, null=True)),
                ('user', models.OneToOneField(help_text='DjangoUser that the info belong to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
