# Generated by Django 3.0.7 on 2020-12-12 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_auto_20201212_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Expertise description', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='bio',
            field=models.TextField(blank=True, help_text='Self-description (degree, biography, ...)', null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='birth_year',
            field=models.IntegerField(blank=True, help_text='Year of birth', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='degree_of_political_engagement',
            field=models.CharField(blank=True, help_text='Your degree of political engagement', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='gender',
            field=models.CharField(blank=True, help_text='Your gender', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='nationality',
            field=models.CharField(blank=True, help_text='Your nationality', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='political_affiliation',
            field=models.CharField(blank=True, help_text='Your political affiliation', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='race',
            field=models.CharField(blank=True, help_text='Your race', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='religion',
            field=models.CharField(blank=True, help_text='Your religion', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='title',
            field=models.TextField(blank=True, help_text='Your position', null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='expertises',
            field=models.ManyToManyField(blank=True, null=True, related_name='expertises', to='backend.Expertise'),
        ),
    ]
