# Generated by Django 3.0.7 on 2020-12-16 08:12

import computed_property.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_auto_20201212_1810_squashed_0059_verifiableemail_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='avatar_hash',
            field=computed_property.fields.ComputedCharField(compute_from='get_avatar_hash', default=uuid.uuid1, editable=False, help_text='Hash for the image.', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='degree_of_political_engagement',
            field=models.CharField(choices=[('Not Specified', 'Not Specified'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Are we ordering fries?', 'Are we ordering fries?')], default='Not Specified', help_text='Your degree of political engagement', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='gender',
            field=models.CharField(choices=[('Not Specified', 'Not Specified'), ('Non-binary', 'Non-binary'), ('Other', 'Other'), ('Female', 'Female'), ('Male', 'Male')], default='Not Specified', help_text='Your gender', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='political_affiliation',
            field=models.CharField(choices=[('Not specified', 'Not specified'), ('Communist', 'Communist'), ('Liberal', 'Liberal'), ('TODO: add more', 'TODO: add more')], default='Not specified', help_text='Your political affiliation', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='race',
            field=models.CharField(choices=[('Not Specified', 'Not Specified'), ('Human', 'Human'), ('Super human', 'Super human'), ('TODO: add more', 'TODO: add more')], default='Not Specified', help_text='Your race', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='religion',
            field=models.CharField(choices=[('Not Specified', 'Not Specified'), ('Atheist', 'Atheist'), ('Christian', 'Christian'), ('Muslim', 'Muslim'), ('TODO: add more', 'TODO: add more')], default='Not Specified', help_text='Your religion', max_length=50),
        ),
        migrations.AlterField(
            model_name='verifiableemail',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified'),
        ),
    ]
