# Generated by Django 3.0.7 on 2020-12-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_auto_20201212_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Expertise keyword description', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='expertise',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='userinformation',
            name='expertise_keywords',
            field=models.ManyToManyField(blank=True, help_text='Your expertis keywords.', null=True, related_name='expertise_keywords', to='backend.Expertise'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='expertises',
            field=models.ManyToManyField(blank=True, help_text='Your expertise.', null=True, related_name='expertises', to='backend.Expertise'),
        ),
    ]
