# Generated by Django 3.0.7 on 2020-12-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_auto_20201216_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='show_my_profile',
            field=models.BooleanField(default=True, help_text='Show my profile on Tournesol'),
        ),
    ]
