# Generated by Django 3.0.7 on 2020-12-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_auto_20201212_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='expertise_keywords',
            field=models.ManyToManyField(blank=True, help_text='Your expertis keywords.', related_name='expertise_keywords', to='backend.Expertise'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='expertises',
            field=models.ManyToManyField(blank=True, help_text='Your expertise.', related_name='expertises', to='backend.Expertise'),
        ),
    ]
