# Generated by Django 3.0.7 on 2020-12-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_userinformation_show_my_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocomment',
            name='anonymous',
            field=models.BooleanField(default=False, help_text="Do not show author's username"),
        ),
    ]
