# Generated by Django 3.0.7 on 2020-12-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_auto_20201221_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildomain',
            name='domain',
            field=models.CharField(help_text='E-mail domain with leading @', max_length=100, unique=True),
        ),
    ]
