# Generated by Django 3.0.7 on 2020-12-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_auto_20201212_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='avatar',
            field=models.ImageField(blank=True, height_field=500, help_text='Your profile picture.', upload_to='profiles', width_field=500),
        ),
    ]
