# Generated by Django 3.0.7 on 2020-12-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_auto_20201221_0757'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='emaildomain',
            name='domain_starts_with_at',
        ),
        migrations.AddConstraint(
            model_name='emaildomain',
            constraint=models.CheckConstraint(check=models.Q(domain__istartswith='@'), name='domain_starts_with_at'),
        ),
    ]
