# Generated by Django 3.0.7 on 2020-12-12 18:47

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_userinformation_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Your profile picture.', upload_to='profiles', validators=[backend.models.UserInformation.validate_avatar]),
        ),
    ]
