# Generated by Django 3.0.7 on 2020-12-13 07:50

import backend.models
import computed_property.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_auto_20201221_0758'),
    ]

    operations = [
    ]
