# Generated by Django 3.0.7 on 2020-12-21 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_fill_email_domains'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaildomain',
            options={'ordering': ['domain']},
        ),
        migrations.AddField(
            model_name='verifiableemail',
            name='domain_fk',
            field=models.ForeignKey(help_text='Foreign key to e-mail domain', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_fk', to='backend.EmailDomain'),
        ),
    ]
