# Generated by Django 3.0.7 on 2020-12-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_auto_20201212_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='E-mail address', max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=False, help_text='If true, this e-mail is verified')),
                ('token', models.CharField(blank=True, help_text='The token that needs to be supplied to verify this e-mail address', max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userinformation',
            name='emails',
            field=models.ManyToManyField(blank=True, help_text='Your e-mail addresses.', related_name='emails', to='backend.VerifiedEmail'),
        ),
    ]
