# Generated by Django 3.0.7 on 2020-12-12 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_verifiedemail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='emails',
        ),
    ]
