# Generated by Django 3.0.7 on 2020-12-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_auto_20201221_0811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaildomain',
            options={'ordering': ['datetime_add', 'domain']},
        ),
        migrations.AddField(
            model_name='emaildomain',
            name='datetime_add',
            field=models.DateTimeField(auto_now_add=True, help_text='Time the domain was added', null=True),
        ),
    ]
