# Generated by Django 3.0.7 on 2020-12-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_auto_20201221_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiableemail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
