# Generated by Django 3.0.7 on 2020-12-12 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_remove_userinformation_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='degrees',
        ),
        migrations.AddField(
            model_name='degree',
            name='useer',
            field=models.ForeignKey(help_text='User that the degree belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.UserInformation'),
        ),
    ]
