# Generated by Django 3.0.7 on 2020-12-12 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_auto_20201212_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='degree',
            old_name='useer',
            new_name='user',
        ),
    ]
