# Generated by Django 3.0.7 on 2020-12-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_auto_20201221_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiableemail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
