# Generated by Django 3.0.7 on 2020-12-12 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_auto_20201212_2127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VerifiedEmail',
            new_name='VerifiableEmail',
        ),
    ]
