# Generated by Django 3.0.7 on 2020-12-21 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0048_auto_20201221_0843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaildomain',
            options={'ordering': ['-datetime_add', 'domain']},
        ),
    ]
