# Generated by Django 3.0.7 on 2020-12-12 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_populate_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiableemail',
            name='user',
            field=models.ForeignKey(default=None, help_text='User that this e-mail belongs to', on_delete=django.db.models.deletion.CASCADE, to='backend.UserInformation'),
            preserve_default=False,
        ),
    ]
