# Generated by Django 3.0.7 on 2020-12-21 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_auto_20201221_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiableemail',
            name='domain_fk',
            field=models.ForeignKey(blank=True, help_text='Foreign key to e-mail domain', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifiable_emails_domain', to='backend.EmailDomain'),
        ),
    ]
