# Generated by Django 3.0.7 on 2020-12-12 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_auto_20201212_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='user',
            field=models.ForeignKey(help_text='User that the degree belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='backend.UserInformation'),
        ),
        migrations.AlterField(
            model_name='verifiableemail',
            name='user',
            field=models.ForeignKey(help_text='User that this e-mail belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='backend.UserInformation'),
        ),
    ]
