# Generated by Django 3.0.7 on 2020-12-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_userinformation_allow_use_in_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='allow_use_in_scores',
            field=models.BooleanField(default=False, help_text='Allow my algorithmic representative to be publicly used for search'),
        ),
    ]
