# Generated by Django 3.0.7 on 2020-12-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_auto_20201221_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='political_affiliation',
            field=models.CharField(choices=[('Not Specified', 'Not Specified'), ('Communist', 'Communist'), ('Liberal', 'Liberal'), ('TODO: add more', 'TODO: add more')], default='Not Specified', help_text='Your political affiliation', max_length=50),
        ),
    ]
