# Generated by Django 3.0.7 on 2020-12-12 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_auto_20201212_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='expertise_keywords',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='expertises',
        ),
        migrations.AddField(
            model_name='expertise',
            name='user',
            field=models.ForeignKey(help_text='User for the expertise', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expertises', to='backend.UserInformation'),
        ),
        migrations.AddField(
            model_name='expertisekeyword',
            name='user',
            field=models.ForeignKey(help_text='User for the expertise keywords', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expertise_keywords', to='backend.UserInformation'),
        ),
    ]
