# Generated by Django 3.0.7 on 2021-01-09 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_auto_20201224_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertrating',
            name='diversity_inclusion',
            field=models.FloatField(blank=True, default=None, help_text='Diversity and Inclusion', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='expertrating',
            name='diversity_inclusion_weight',
            field=models.FloatField(default=1, help_text='Diversity and Inclusion weight', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='expertrating',
            name='layman_friendly',
            field=models.FloatField(blank=True, default=None, help_text='Layman-friendly', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='expertrating',
            name='layman_friendly_weight',
            field=models.FloatField(default=1, help_text='Layman-friendly weight', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='diversity_inclusion',
            field=models.FloatField(default=0, help_text='Diversity and Inclusion', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='layman_friendly',
            field=models.FloatField(default=0, help_text='Layman-friendly', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='video',
            name='diversity_inclusion',
            field=models.FloatField(default=None, help_text='Diversity and Inclusion', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='layman_friendly',
            field=models.FloatField(default=None, help_text='Layman-friendly', null=True),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='diversity_inclusion',
            field=models.BooleanField(default=False, help_text='Diversity and Inclusion', null=True),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='layman_friendly',
            field=models.BooleanField(default=False, help_text='Layman-friendly', null=True),
        ),
        migrations.AddField(
            model_name='videorating',
            name='diversity_inclusion',
            field=models.FloatField(blank=True, default=None, help_text='Diversity and Inclusion', null=True),
        ),
        migrations.AddField(
            model_name='videorating',
            name='layman_friendly',
            field=models.FloatField(blank=True, default=None, help_text='Layman-friendly', null=True),
        ),
        migrations.AlterField(
            model_name='expertrating',
            name='backfire_risk',
            field=models.FloatField(blank=True, default=None, help_text='Resilience to backfiring risks', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='expertrating',
            name='engaging',
            field=models.FloatField(blank=True, default=None, help_text='Engaging', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='expertrating',
            name='importance',
            field=models.FloatField(blank=True, default=None, help_text='Importance', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='expertrating',
            name='pedagogy',
            field=models.FloatField(blank=True, default=None, help_text='Pedagogy', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='expertrating',
            name='reliability',
            field=models.FloatField(blank=True, default=None, help_text='Reliability', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='video',
            name='backfire_risk',
            field=models.FloatField(default=None, help_text='Resilience to backfiring risks', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='engaging',
            field=models.FloatField(default=None, help_text='Engaging', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='importance',
            field=models.FloatField(default=None, help_text='Importance', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='pedagogy',
            field=models.FloatField(default=None, help_text='Pedagogy', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='reliability',
            field=models.FloatField(default=None, help_text='Reliability', null=True),
        ),
        migrations.AlterField(
            model_name='videorating',
            name='backfire_risk',
            field=models.FloatField(blank=True, default=None, help_text='Resilience to backfiring risks', null=True),
        ),
        migrations.AlterField(
            model_name='videorating',
            name='engaging',
            field=models.FloatField(blank=True, default=None, help_text='Engaging', null=True),
        ),
        migrations.AlterField(
            model_name='videorating',
            name='importance',
            field=models.FloatField(blank=True, default=None, help_text='Importance', null=True),
        ),
        migrations.AlterField(
            model_name='videorating',
            name='pedagogy',
            field=models.FloatField(blank=True, default=None, help_text='Pedagogy', null=True),
        ),
        migrations.AlterField(
            model_name='videorating',
            name='reliability',
            field=models.FloatField(blank=True, default=None, help_text='Reliability', null=True),
        ),
    ]
