# Generated by Django 3.0.7 on 2020-12-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_auto_20201212_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='name',
            field=models.CharField(help_text='Expertise description', max_length=100),
        ),
        migrations.AlterField(
            model_name='expertisekeyword',
            name='name',
            field=models.CharField(help_text='Expertise keyword description', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='expertise',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='expertisekeyword',
            unique_together={('name', 'user')},
        ),
    ]
