# Generated by Django 3.0.7 on 2021-01-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0055_auto_20210109_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorating',
            name='backfire_risk',
            field=models.FloatField(default=0, help_text='Resilience to backfiring risks'),
        ),
        migrations.AlterField(
            model_name='videorating',
            name='diversity_inclusion',
            field=models.FloatField(default=0, help_text='Diversity and Inclusion'),
        ),
        migrations.AlterField(
            model_name='videorating',
            name='engaging',
            field=models.FloatField(default=0, help_text='Engaging'),
        ),
        migrations.AlterField(
            model_name='videorating',
            name='importance',
            field=models.FloatField(default=0, help_text='Importance'),
        ),
        migrations.AlterField(
            model_name='videorating',
            name='layman_friendly',
            field=models.FloatField(default=0, help_text='Layman-friendly'),
        ),
        migrations.AlterField(
            model_name='videorating',
            name='pedagogy',
            field=models.FloatField(default=0, help_text='Pedagogy'),
        ),
        migrations.AlterField(
            model_name='videorating',
            name='reliability',
            field=models.FloatField(default=0, help_text='Reliability'),
        ),
    ]
