# Generated by Django 3.0.7 on 2020-12-13 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0056_auto_20201213_0041'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='verifiableemail',
            unique_together={('email', 'user')},
        ),
    ]
