# Generated by Django 3.0.7 on 2021-01-10 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0056_auto_20210109_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepresentativeModelUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(help_text='Model used for search', on_delete=django.db.models.deletion.CASCADE, related_name='model_usage_of', to='backend.UserPreferences')),
                ('viewer', models.ForeignKey(help_text='Person using the model for search', on_delete=django.db.models.deletion.CASCADE, related_name='model_usage_by', to='backend.UserPreferences')),
            ],
            options={
                'unique_together': {('model', 'viewer')},
            },
        ),
    ]
