# Generated by Django 3.0.7 on 2021-01-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_representativemodelusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='researchgate',
            field=models.URLField(blank=True, help_text='Your Researchgate profile URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='orcid',
            field=models.URLField(blank=True, help_text='Your ORCID URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='twitter',
            field=models.URLField(blank=True, help_text='Your Twitter URL', max_length=500, null=True),
        ),
    ]
