# Generated by Django 3.0.7 on 2020-12-13 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_auto_20201213_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiableemail',
            name='user',
            field=models.ForeignKey(help_text='User that this e-mail belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='backend.UserInformation'),
        ),
    ]
