# Generated by Django 3.0.7 on 2020-12-13 07:45

import computed_property.fields
from django.db import migrations
from backend.models import VerifiableEmail
import uuid

def recompute_property(*args, **kwargs):
    """Open all objects and save them to recompute the property."""
    for instance in VerifiableEmail.objects.all().iterator():
        val = instance.domain
        print(val)
        instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0058_auto_20201213_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiableemail',
            name='domain',
            field=computed_property.fields.ComputedCharField(compute_from='email_domain', default=uuid.uuid1, editable=False, help_text='Email domain with @', max_length=50),
        ),
        migrations.RunPython(recompute_property),
    ]
