# Generated by Django 3.0.7 on 2021-01-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_auto_20210114_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertrating',
            name='datetime_add',
            field=models.DateTimeField(auto_now_add=True, help_text='Time the rating was added', null=True),
        ),
        migrations.AlterField(
            model_name='expertrating',
            name='datetime_lastedit',
            field=models.DateTimeField(blank=True, help_text='Time the rating was edited the last time', null=True),
        ),
    ]
