# Generated by Django 3.0.7 on 2021-01-14 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_auto_20210114_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSelectorSkips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_add', models.DateTimeField(auto_now_add=True, help_text='Time the video was skipped', null=True)),
                ('user', models.ForeignKey(help_text='Person who skips the videos', on_delete=django.db.models.deletion.CASCADE, related_name='skipped_videos', to='backend.UserPreferences')),
                ('video', models.ForeignKey(help_text='Video being skipped', on_delete=django.db.models.deletion.CASCADE, related_name='skips', to='backend.Video')),
            ],
        ),
    ]
