# Generated by Django 3.0.7 on 2021-01-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0061_videoselectorskips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='race',
            field=models.CharField(choices=[('Not Specified', 'Not Specified'), ('African', 'African'), ('African American', 'African American'), ('American Indian', 'American Indian'), ('Arabic or Middle Eastern', 'Arabic or Middle Eastern'), ('Asian', 'Asian'), ('Caucasian', 'Caucasian'), ('Latino or Hispanic', 'Latino or Hispanic'), ('Mixed', 'Mixed'), ('Unknown', 'Unknown'), ('Other', 'Other')], default='Not Specified', help_text='Your ethnicity', max_length=50),
        ),
    ]
