# Generated by Django 3.0.7 on 2021-02-10 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0064_expertratingsliderchanges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertratingsliderchanges',
            name='rating',
        ),
        migrations.AddField(
            model_name='expertratingsliderchanges',
            name='user',
            field=models.ForeignKey(help_text='Person changing the sliders', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.UserPreferences'),
        ),
        migrations.AddField(
            model_name='expertratingsliderchanges',
            name='video_left',
            field=models.ForeignKey(help_text='Left video', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_left', to='backend.Video'),
        ),
        migrations.AddField(
            model_name='expertratingsliderchanges',
            name='video_right',
            field=models.ForeignKey(help_text='Right video', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_right', to='backend.Video'),
        ),
    ]
