# Generated by Django 3.0.7 on 2021-02-10 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0065_auto_20210210_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRatingThankYou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thanks_from', models.ForeignKey(help_text='Who thanks for the video', on_delete=django.db.models.deletion.CASCADE, related_name='thanks_from', to='backend.UserPreferences')),
                ('thanks_to', models.ForeignKey(help_text='Who receives the thanks', on_delete=django.db.models.deletion.CASCADE, related_name='thanks_to', to='backend.UserPreferences')),
                ('video', models.ForeignKey(help_text='Video thanked for', on_delete=django.db.models.deletion.CASCADE, to='backend.Video')),
            ],
            options={
                'unique_together': {('video', 'thanks_from', 'thanks_to')},
            },
        ),
    ]
