# Generated by Django 3.0.7 on 2021-02-10 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0066_videoratingthankyou'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRatingPrivacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False, help_text='Should the rating be public?')),
                ('user', models.ForeignKey(help_text='User who rates videos', on_delete=django.db.models.deletion.CASCADE, to='backend.UserPreferences')),
                ('video', models.ForeignKey(help_text='Video whose rating is either private or public', on_delete=django.db.models.deletion.CASCADE, to='backend.Video')),
            ],
            options={
                'unique_together': {('user', 'video')},
            },
        ),
    ]
