# Generated by Django 3.0.7 on 2021-02-10 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0068_auto_20210210_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRateLater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_add', models.DateTimeField(auto_now_add=True, help_text='Time the video was added to the rate later list', null=True)),
                ('user', models.ForeignKey(help_text='Person who saves the video', on_delete=django.db.models.deletion.CASCADE, to='backend.UserPreferences')),
                ('video', models.ForeignKey(help_text='Video in the rate later list', on_delete=django.db.models.deletion.CASCADE, to='backend.Video')),
            ],
            options={
                'ordering': ['user', 'datetime_add', 'video'],
                'unique_together': {('user', 'video')},
            },
        ),
    ]
