# Generated by Django 3.0.7 on 2021-02-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0069_videoratelater'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoratelater',
            options={'ordering': ['user', '-datetime_add']},
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='backfire_risk_enabled',
            field=models.BooleanField(default=True, help_text='backfire_risk given for ratings'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='diversity_inclusion_enabled',
            field=models.BooleanField(default=True, help_text='diversity_inclusion given for ratings'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='engaging_enabled',
            field=models.BooleanField(default=True, help_text='engaging given for ratings'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='importance_enabled',
            field=models.BooleanField(default=True, help_text='importance given for ratings'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='layman_friendly_enabled',
            field=models.BooleanField(default=True, help_text='layman_friendly given for ratings'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='pedagogy_enabled',
            field=models.BooleanField(default=True, help_text='pedagogy given for ratings'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='rating_mode',
            field=models.CharField(choices=[('enable_all', 'enable_all'), ('skip', 'skip'), ('confidence', 'confidence')], default='enable_all', help_text='Which sliders and parameters to display on the rating page?', max_length=50),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='reliability_enabled',
            field=models.BooleanField(default=True, help_text='reliability given for ratings'),
        ),
    ]
