# Generated by Django 3.0.7 on 2021-02-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0071_auto_20210211_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='backfire_risk_enabled',
            field=models.BooleanField(default=False, help_text='backfire_risk given for ratings'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='better_habits_enabled',
            field=models.BooleanField(default=False, help_text='better_habits given for ratings'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='diversity_inclusion_enabled',
            field=models.BooleanField(default=False, help_text='diversity_inclusion given for ratings'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='layman_friendly_enabled',
            field=models.BooleanField(default=False, help_text='layman_friendly given for ratings'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='pedagogy_enabled',
            field=models.BooleanField(default=False, help_text='pedagogy given for ratings'),
        ),
    ]
