# Generated by Django 3.0.7 on 2021-02-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0072_auto_20210211_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='backfire_risk_uncertainty',
            field=models.FloatField(default=0, help_text='Uncertainty for backfire_risk'),
        ),
        migrations.AddField(
            model_name='video',
            name='better_habits_uncertainty',
            field=models.FloatField(default=0, help_text='Uncertainty for better_habits'),
        ),
        migrations.AddField(
            model_name='video',
            name='diversity_inclusion_uncertainty',
            field=models.FloatField(default=0, help_text='Uncertainty for diversity_inclusion'),
        ),
        migrations.AddField(
            model_name='video',
            name='engaging_uncertainty',
            field=models.FloatField(default=0, help_text='Uncertainty for engaging'),
        ),
        migrations.AddField(
            model_name='video',
            name='importance_uncertainty',
            field=models.FloatField(default=0, help_text='Uncertainty for importance'),
        ),
        migrations.AddField(
            model_name='video',
            name='layman_friendly_uncertainty',
            field=models.FloatField(default=0, help_text='Uncertainty for layman_friendly'),
        ),
        migrations.AddField(
            model_name='video',
            name='pedagogy_uncertainty',
            field=models.FloatField(default=0, help_text='Uncertainty for pedagogy'),
        ),
        migrations.AddField(
            model_name='video',
            name='reliability_uncertainty',
            field=models.FloatField(default=0, help_text='Uncertainty for reliability'),
        ),
        migrations.AddField(
            model_name='videorating',
            name='backfire_risk_uncertainty',
            field=models.FloatField(default=0, help_text='Uncertainty for backfire_risk'),
        ),
        migrations.AddField(
            model_name='videorating',
            name='better_habits_uncertainty',
            field=models.FloatField(default=0, help_text='Uncertainty for better_habits'),
        ),
        migrations.AddField(
            model_name='videorating',
            name='diversity_inclusion_uncertainty',
            field=models.FloatField(default=0, help_text='Uncertainty for diversity_inclusion'),
        ),
        migrations.AddField(
            model_name='videorating',
            name='engaging_uncertainty',
            field=models.FloatField(default=0, help_text='Uncertainty for engaging'),
        ),
        migrations.AddField(
            model_name='videorating',
            name='importance_uncertainty',
            field=models.FloatField(default=0, help_text='Uncertainty for importance'),
        ),
        migrations.AddField(
            model_name='videorating',
            name='layman_friendly_uncertainty',
            field=models.FloatField(default=0, help_text='Uncertainty for layman_friendly'),
        ),
        migrations.AddField(
            model_name='videorating',
            name='pedagogy_uncertainty',
            field=models.FloatField(default=0, help_text='Uncertainty for pedagogy'),
        ),
        migrations.AddField(
            model_name='videorating',
            name='reliability_uncertainty',
            field=models.FloatField(default=0, help_text='Uncertainty for reliability'),
        ),
    ]
