# Generated by Django 3.0.7 on 2021-02-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0073_auto_20210211_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(help_text='Video ID from YouTube URL, matches [A-Za-z0-9-_]', max_length=20, unique=True),
        ),
    ]
