# Generated by Django 3.0.7 on 2021-02-12 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0074_auto_20210212_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(help_text='Video ID from YouTube URL, matches [A-Za-z0-9-_]', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9-_]+$', 'Video ID characters must match [A-Za-z0-9-_]')]),
        ),
    ]
