# Generated by Django 3.0.7 on 2021-02-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0078_auto_20210212_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='metadata_timestamp',
            field=models.DateTimeField(help_text='Timestamp the metadata was uploaded', null=True),
        ),
    ]
