# Generated by Django 3.0.7 on 2021-02-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0079_video_metadata_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='wrong_url',
            field=models.BooleanField(default=False, help_text='Is the URL incorrect'),
        ),
    ]
