# Generated by Django 3.0.7 on 2021-02-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0080_video_wrong_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_unlisted',
            field=models.BooleanField(default=False, help_text='Is the video unlisted'),
        ),
    ]
