# Generated by Django 3.0.7 on 2021-02-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0081_video_is_unlisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='download_failed',
            field=models.BooleanField(default=False, help_text='Was last download unsuccessful'),
        ),
    ]
