# Generated by Django 3.0.7 on 2021-03-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0082_video_download_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='download_attempts',
            field=models.IntegerField(default=0, help_text='Number of times video was downloaded'),
        ),
        migrations.AddField(
            model_name='video',
            name='last_download_time',
            field=models.DateTimeField(help_text='Last time download of metadata was attempted', null=True),
        ),
    ]
