# Generated by Django 3.0.7 on 2021-03-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0084_video_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Time the video was added to Tournesol', null=True),
        ),
    ]
