# Generated by Django 3.0.7 on 2021-03-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0085_auto_20210308_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='last_download_time',
            field=models.DateTimeField(blank=True, help_text='Last time download of metadata was attempted', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='metadata_timestamp',
            field=models.DateTimeField(blank=True, help_text='Timestamp the metadata was uploaded', null=True),
        ),
    ]
