# Generated by Django 3.1.7 on 2021-03-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0086_auto_20210308_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Is a demo account?'),
        ),
    ]
