# Generated by Django 3.1.7 on 2021-03-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0087_userinformation_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertratingsliderchanges',
            name='context',
            field=models.CharField(choices=[('RATE', 'RATE'), ('DIS', 'DIS'), ('INC', 'INC')], default='RATE', help_text='The page where slider change occurs', max_length=10),
        ),
        migrations.AddField(
            model_name='expertratingsliderchanges',
            name='duration_ms',
            field=models.FloatField(default=0, help_text='Time from page load to this slider value (in milliseconds)', null=True),
        ),
    ]
