# Generated by Django 3.0.7 on 2021-03-09 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0088_auto_20210309_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='allow_use_in_scores',
        ),
    ]
