# Generated by Django 3.1.6 on 2021-04-12 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0089_remove_userinformation_allow_use_in_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertrating',
            name='entertaining_relaxing',
            field=models.FloatField(blank=True, default=None, help_text='Entertaining and relaxing', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='expertrating',
            name='entertaining_relaxing_weight',
            field=models.FloatField(default=1, help_text='Entertaining and relaxing weight', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='expertratingsliderchanges',
            name='entertaining_relaxing',
            field=models.FloatField(blank=True, default=None, help_text='Entertaining and relaxing', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='entertaining_relaxing',
            field=models.FloatField(default=0, help_text='Entertaining and relaxing', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='entertaining_relaxing_enabled',
            field=models.BooleanField(default=False, help_text='entertaining_relaxing given for ratings'),
        ),
        migrations.AddField(
            model_name='video',
            name='entertaining_relaxing',
            field=models.FloatField(default=0, help_text='Entertaining and relaxing'),
        ),
        migrations.AddField(
            model_name='video',
            name='entertaining_relaxing_uncertainty',
            field=models.FloatField(default=0, help_text='Uncertainty for entertaining_relaxing'),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='entertaining_relaxing',
            field=models.BooleanField(default=False, help_text='Entertaining and relaxing', null=True),
        ),
        migrations.AddField(
            model_name='videorating',
            name='entertaining_relaxing',
            field=models.FloatField(default=0, help_text='Entertaining and relaxing'),
        ),
        migrations.AddField(
            model_name='videorating',
            name='entertaining_relaxing_uncertainty',
            field=models.FloatField(default=0, help_text='Uncertainty for entertaining_relaxing'),
        ),
    ]
