# Generated by Django 3.1.8 on 2021-04-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0090_auto_20210412_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='google_scholar',
            field=models.URLField(blank=True, default=None, help_text='Your Google Scholar URL', max_length=500, null=True),
        ),
    ]
