# Generated by Django 3.1.8 on 2021-05-02 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0092_verifiableemail_last_verification_email_ts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoReports',
        ),
    ]
