# Generated by Django 3.1.8 on 2021-05-04 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0095_auto_20210504_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='backfire_risk_quantile',
            field=models.FloatField(blank=True, default=None, help_text='Top quantile for backfire_risk for all rated videos for aggregated scores. 0.0=best, 1.0=worst', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='video',
            name='better_habits_quantile',
            field=models.FloatField(blank=True, default=None, help_text='Top quantile for better_habits for all rated videos for aggregated scores. 0.0=best, 1.0=worst', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='video',
            name='diversity_inclusion_quantile',
            field=models.FloatField(blank=True, default=None, help_text='Top quantile for diversity_inclusion for all rated videos for aggregated scores. 0.0=best, 1.0=worst', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='video',
            name='engaging_quantile',
            field=models.FloatField(blank=True, default=None, help_text='Top quantile for engaging for all rated videos for aggregated scores. 0.0=best, 1.0=worst', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='video',
            name='entertaining_relaxing_quantile',
            field=models.FloatField(blank=True, default=None, help_text='Top quantile for entertaining_relaxing for all rated videos for aggregated scores. 0.0=best, 1.0=worst', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='video',
            name='importance_quantile',
            field=models.FloatField(blank=True, default=None, help_text='Top quantile for importance for all rated videos for aggregated scores. 0.0=best, 1.0=worst', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='video',
            name='layman_friendly_quantile',
            field=models.FloatField(blank=True, default=None, help_text='Top quantile for layman_friendly for all rated videos for aggregated scores. 0.0=best, 1.0=worst', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='video',
            name='pedagogy_quantile',
            field=models.FloatField(blank=True, default=None, help_text='Top quantile for pedagogy for all rated videos for aggregated scores. 0.0=best, 1.0=worst', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='video',
            name='reliability_quantile',
            field=models.FloatField(blank=True, default=None, help_text='Top quantile for reliability for all rated videos for aggregated scores. 0.0=best, 1.0=worst', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
