# Generated by Django 3.1.8 on 2021-05-04 17:16

import backend.model_helpers
import computed_property.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0096_auto_20210504_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_update_pending',
            field=models.BooleanField(default=False, help_text='If true, recompute properties'),
        ),
        migrations.AlterField(
            model_name='video',
            name='public_experts',
            field=backend.model_helpers.ComputedJsonField(compute_from='get_certified_top_raters_list', default='[]', editable=False, help_text='Top 10 certified public contributor usernames'),
        ),
        migrations.AlterField(
            model_name='video',
            name='rating_n_ratings',
            field=computed_property.fields.ComputedIntegerField(compute_from='get_rating_n_ratings', default=0, editable=False, help_text='Total number of pairwise comparisons for this video from certified contributors'),
        ),
    ]
