# These are the supported funding platforms.
#
# Direct transfers without extra fee are also available on the tournesol.app
# donation page.
#
#   See: https://tournesol.app/about/donate

custom: ['https://www.kisskissbankbank.com/en/projects/tournesol-9c3fce6a-261b-4bf2-a147-f72b39b2737a', 'https://www.paypal.com/paypalme/tournesolapp', 'https://tournesol.app/about/donate']
