/**
 * Tournesol API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TournesolApi);
  }
}(this, function(expect, TournesolApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TournesolApi.ExpertRatingsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ExpertRatingsApi', function() {
    describe('apiV2ExpertRatingsDoubleDown', function() {
      it('should call apiV2ExpertRatingsDoubleDown successfully', function(done) {
        //uncomment below and update the code to test apiV2ExpertRatingsDoubleDown
        //instance.apiV2ExpertRatingsDoubleDown(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV2ExpertRatingsSampleVideo', function() {
      it('should call apiV2ExpertRatingsSampleVideo successfully', function(done) {
        //uncomment below and update the code to test apiV2ExpertRatingsSampleVideo
        //instance.apiV2ExpertRatingsSampleVideo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV2ExpertRatingsShowInconsistencies', function() {
      it('should call apiV2ExpertRatingsShowInconsistencies successfully', function(done) {
        //uncomment below and update the code to test apiV2ExpertRatingsShowInconsistencies
        //instance.apiV2ExpertRatingsShowInconsistencies(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('expertRatingsByVideoIdsPartialUpdate', function() {
      it('should call expertRatingsByVideoIdsPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test expertRatingsByVideoIdsPartialUpdate
        //instance.expertRatingsByVideoIdsPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('expertRatingsByVideoIdsRetrieve', function() {
      it('should call expertRatingsByVideoIdsRetrieve successfully', function(done) {
        //uncomment below and update the code to test expertRatingsByVideoIdsRetrieve
        //instance.expertRatingsByVideoIdsRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('expertRatingsCreate', function() {
      it('should call expertRatingsCreate successfully', function(done) {
        //uncomment below and update the code to test expertRatingsCreate
        //instance.expertRatingsCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('expertRatingsList', function() {
      it('should call expertRatingsList successfully', function(done) {
        //uncomment below and update the code to test expertRatingsList
        //instance.expertRatingsList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('expertRatingsPartialUpdate', function() {
      it('should call expertRatingsPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test expertRatingsPartialUpdate
        //instance.expertRatingsPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('expertRatingsRetrieve', function() {
      it('should call expertRatingsRetrieve successfully', function(done) {
        //uncomment below and update the code to test expertRatingsRetrieve
        //instance.expertRatingsRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('expertRatingsUpdate', function() {
      it('should call expertRatingsUpdate successfully', function(done) {
        //uncomment below and update the code to test expertRatingsUpdate
        //instance.expertRatingsUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
