/**
 * Tournesol API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TournesolApi);
  }
}(this, function(expect, TournesolApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TournesolApi.UserPreferencesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserPreferencesApi', function() {
    describe('userPreferencesList', function() {
      it('should call userPreferencesList successfully', function(done) {
        //uncomment below and update the code to test userPreferencesList
        //instance.userPreferencesList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userPreferencesMyPartialUpdate', function() {
      it('should call userPreferencesMyPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test userPreferencesMyPartialUpdate
        //instance.userPreferencesMyPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userPreferencesMyRetrieve', function() {
      it('should call userPreferencesMyRetrieve successfully', function(done) {
        //uncomment below and update the code to test userPreferencesMyRetrieve
        //instance.userPreferencesMyRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userPreferencesPartialUpdate', function() {
      it('should call userPreferencesPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test userPreferencesPartialUpdate
        //instance.userPreferencesPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userPreferencesRetrieve', function() {
      it('should call userPreferencesRetrieve successfully', function(done) {
        //uncomment below and update the code to test userPreferencesRetrieve
        //instance.userPreferencesRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userPreferencesUpdate', function() {
      it('should call userPreferencesUpdate successfully', function(done) {
        //uncomment below and update the code to test userPreferencesUpdate
        //instance.userPreferencesUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
