repos:
- repo: local
  hooks:
    - id: backend_isort
      name: 'backend: isort'
      entry: isort
      args: ['--check-only']
      language: system
      files: '^backend/'
      types: [file, python]
      require_serial: true
    - id: backend_pylint
      name: 'backend: pylint'
      entry: pylint
      args: ['--rcfile=backend/.pylintrc']
      language: system
      files: '^backend/'
      types: [file, python]
      require_serial: true
    - id: backend_flake8
      name: 'backend: flake8'
      entry: flake8
      args: ['--config=backend/.flake8']
      language: system
      files: '^backend/'
      types: [file, python]
      require_serial: true
