# Generated by Django 3.2.11 on 2022-02-02 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournesol', '0018_fill_missing_video_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(help_text='Tweet ID from Twitter URL', max_length=22)),
                ('datetime_tweet', models.DateTimeField(auto_now_add=True, help_text='Time when the video was tweeted', null=True)),
                ('bot_name', models.CharField(blank=True, choices=[('@TournesolBot', '@TournesolBot'), ('@TournesolBotFR', '@TournesolBotFR')], help_text='Name of the twitter bot', max_length=200, null=True)),
                ('video', models.ForeignKey(help_text='Tweeted video', on_delete=django.db.models.deletion.CASCADE, related_name='video', to='tournesol.video')),
            ],
        ),
    ]
