# Generated by Django 4.0.3 on 2022-03-13 17:06

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0032_alter_entity_type_alter_poll_entity_type'),
        ('twitterbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TweetedVideo',
            new_name='TweetInfo',
        ),
        migrations.AlterField(
            model_name='tweetinfo',
            name='video',
            field=models.ForeignKey(help_text='Tweeted video', on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='tournesol.entity'),
        ),
    ]
