# Generated by Django 4.2.18 on 2025-02-06 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tournesol", "0061_comparisoncriteriascore_score_max_and_more"),
        ("twitterbot", "0003_tweetinfo_atproto_uri_alter_tweetinfo_tweet_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweetinfo",
            name="bot_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("@TournesolBot", "@TournesolBot"),
                    ("@TournesolBotFR", "@TournesolBotFR"),
                ],
                help_text="Name of the bot",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tweetinfo",
            name="datetime_tweet",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Time when the video was posted", null=True
            ),
        ),
        migrations.AlterField(
            model_name="tweetinfo",
            name="video",
            field=models.ForeignKey(
                help_text="Posted video",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tweets",
                to="tournesol.entity",
            ),
        ),
    ]
