- name: Reload Nginx
  systemd:
    name: nginx
    state: reloaded
    daemon_reload: yes

- name: Restart Grafana
  systemd:
    name: grafana-server
    state: restarted
    daemon_reload: yes

- name: Restart Loki
  systemd:
    name: loki
    state: restarted
    daemon_reload: yes

- name: Restart Promtail
  systemd:
    name: promtail
    state: restarted
    daemon_reload: yes
