# Generated by Django 4.1.9 on 2023-06-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TalkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='the reference of the talk', unique=True)),
                ('date', models.DateTimeField(blank=True, default=None, help_text='Timestamp when the talk will take place or its broadcast date', null=True)),
                ('invitation_link', models.URLField(blank=True, help_text='the invitation link of the talk', null=True)),
                ('youtube_link', models.URLField(blank=True, help_text='the youtube link of the talk', null=True)),
                ('speaker', models.CharField(blank=True, help_text='the speaker of the talk', max_length=50, null=True)),
                ('speaker_short_desc', models.CharField(blank=True, help_text='A short biography of speaker', max_length=50, null=True)),
                ('title', models.CharField(blank=True, help_text='the title of the talk', max_length=255, null=True)),
                ('abstract', models.TextField(blank=True, help_text='Description of the content of the talk', null=True)),
                ('display', models.BooleanField(default=False, help_text='Determine if talk is display on frontend')),
            ],
            options={
                'verbose_name': 'Talk Entry',
                'verbose_name_plural': 'Talk Entries',
                'ordering': ['date'],
            },
        ),
    ]
