# Generated by Django 4.1.9 on 2023-06-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_remove_talkentry_speaker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkentry',
            name='date',
            field=models.DateTimeField(blank=True, default=None,
                                       help_text='Date and time when the talk (please mind the server time zone).',
                                       null=True),
        ),
        migrations.AlterField(
            model_name='talkentry',
            name='name',
            field=models.SlugField(help_text='Unique reference of the talk', unique=True),
        ),
    ]
