# Generated by Django 4.1.9 on 2023-06-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0003_alter_talkentry_date_alter_talkentry_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="talkentry",
            options={
                "ordering": ["-date"],
                "verbose_name": "Talk Entry",
                "verbose_name_plural": "Talk Entries",
            },
        ),
        migrations.AlterField(
            model_name="talkentry",
            name="abstract",
            field=models.TextField(blank=True, help_text="Description of the Talk.", null=True),
        ),
        migrations.AlterField(
            model_name="talkentry",
            name="date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time of the Talk (please mind the server time zone).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="talkentry",
            name="display",
            field=models.BooleanField(
                default=False, help_text="If False, the Talk should not be returned by the API."
            ),
        ),
        migrations.AlterField(
            model_name="talkentry",
            name="invitation_link",
            field=models.URLField(
                blank=True, help_text="Allow the users to join the Talk.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="talkentry",
            name="name",
            field=models.SlugField(
                help_text="Unique identifier of the Talk (usable as an URL slug).", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="talkentry",
            name="speakers",
            field=models.TextField(
                blank=True,
                help_text="A list of speakers and their titles (researcher, PhD student, etc.).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="talkentry",
            name="title",
            field=models.CharField(default="", help_text="The title of the Talk.", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="talkentry",
            name="youtube_link",
            field=models.URLField(blank=True, help_text="The Talk's YouTube link.", null=True),
        ),
    ]
