# Generated by Django 4.1.9 on 2023-06-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0004_to_0005_title_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talkentry",
            name="name",
            field=models.SlugField(
                blank=True,
                help_text="Used as an URL slug. Leave it blank to automatically build it from the title.",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="talkentry",
            name="title",
            field=models.CharField(
                help_text="The title of the Talk.", max_length=255, unique=True
            ),
        ),
    ]
