# Generated by Django 4.1.9 on 2023-06-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0005_make_title_unique"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="talkentry",
            name="private",
        ),
        migrations.AddField(
            model_name="talkentry",
            name="public",
            field=models.BooleanField(
                default=False, help_text="If False, the Talk should not be returned by the API."
            ),
        ),
    ]
