# Generated by Django 4.1.9 on 2023-06-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0005_to_0006_make_title_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talkentry",
            name="date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time of the Talk according to the server time.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="talkentry",
            name="invitation_link",
            field=models.URLField(
                blank=True, help_text="Allows the users to join the Talk.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="talkentry",
            name="name",
            field=models.SlugField(
                blank=True,
                help_text="Used as an URL slug. Leave it blank to automatically build it from the title.",
                max_length=255,
                unique=True,
            ),
        ),
    ]
