# Generated by Django 4.1.9 on 2023-07-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0007_0008_banner_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bannerlocale",
            old_name="url",
            new_name="action_link",
        ),
    ]
