# Generated by Django 4.1.9 on 2023-06-29 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0007_banner_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banner",
            options={"ordering": ["-date_start", "-date_end", "-priority"]},
        ),
        migrations.AlterField(
            model_name="banner",
            name="date_end",
            field=models.DateTimeField(
                help_text="After this date the banner should not be returned by the API."
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="date_start",
            field=models.DateTimeField(
                help_text="Date on which the banner should be returned by the API."
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="enabled",
            field=models.BooleanField(
                default=True, help_text="Disabled banner should not be returned by the API."
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="name",
            field=models.CharField(help_text="The banner's name.", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="banner",
            name="priority",
            field=models.IntegerField(default=1, help_text="Allows to order the banners."),
        ),
        migrations.AlterField(
            model_name="banner",
            name="security_advisory",
            field=models.BooleanField(
                default=False, help_text="If True the banner is a security announcement."
            ),
        ),
        migrations.AlterField(
            model_name="banneractionlink",
            name="banner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action_links",
                to="backoffice.banner",
            ),
        ),
    ]
