# Generated by Django 4.1.9 on 2023-07-03 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0007_banner_bannerlocale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerlocale',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='backoffice.banner'),
        ),
    ]
