# Generated by Django 4.1.9 on 2023-07-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0008_rename_url_bannerlocale_action_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bannerlocale",
            name="action_label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bannerlocale",
            name="action_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
