# Generated by Django 4.1.9 on 2023-06-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0008_remove_extra_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="priority",
            field=models.IntegerField(default=5, help_text="Allows to order the banners."),
        ),
    ]
