# Generated by Django 4.1.10 on 2023-07-11 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0010_init_faq"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FAQAnswerLocale",
        ),
        migrations.DeleteModel(
            name="FAQEntry",
        ),
        migrations.DeleteModel(
            name="FAQuestionLocale",
        ),
    ]
