# Generated by Django 4.1.10 on 2023-07-11 12:26

from django.db import migrations


def migrate_forward(apps, schema_editor):
    """
    This migration used to migrate the data from the legacy `faq` app to the
    `backoffice`. The app `faq` doesn't exist anymore, and all references to
    it have been deleted.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0012_rebuild_faq"),
    ]

    operations = [migrations.RunPython(migrate_forward, migrations.RunPython.noop)]
