# Generated by Django 4.1.10 on 2023-07-11 12:26

from django.db import migrations


def migrate_forward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0012_rebuild_faq"),
    ]

    operations = [migrations.RunPython(migrate_forward, migrations.RunPython.noop)]
