# Generated by Django 4.1.10 on 2023-08-31 08:28

from django.db import connection, migrations
from django.db.utils import ProgrammingError


def migrate_forward(apps, schema_editor):
    with connection.cursor() as cursor:
        try:
            cursor.execute("DROP TABLE faq_faqanswerlocale")
            cursor.execute("DROP TABLE faq_faquestionlocale")
            cursor.execute("DROP TABLE faq_faqentry")
        except ProgrammingError:
            pass


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("backoffice", "0013_move_data_from_faq_to_backoffice"),
    ]

    operations = [migrations.RunPython(migrate_forward, migrations.RunPython.noop)]
