# Generated by Django 4.2.10 on 2024-02-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0015_alter_bannerlocale_language_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="talkentry",
            options={"ordering": ["-date"], "verbose_name": "Tournesol Event"},
        ),
        migrations.AddField(
            model_name="talkentry",
            name="event_type",
            field=models.CharField(
                choices=[("live", "Tournesol Live"), ("talk", "Tournesol Talk")],
                default="talk",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="talkentry",
            name="abstract",
            field=models.TextField(blank=True, help_text="Description of the event.", null=True),
        ),
        migrations.AlterField(
            model_name="talkentry",
            name="date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time of the event according to the server time.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="talkentry",
            name="invitation_link",
            field=models.URLField(
                blank=True, help_text="Allows the users to join the event.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="talkentry",
            name="public",
            field=models.BooleanField(
                default=False, help_text="If False, the event should not be returned by the API."
            ),
        ),
        migrations.AlterField(
            model_name="talkentry",
            name="title",
            field=models.CharField(
                help_text="The title of the event.", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="talkentry",
            name="youtube_link",
            field=models.URLField(
                blank=True, help_text="The YouTube link of the recorded event.", null=True
            ),
        ),
    ]
