/**
 * Tournesol API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ConstantsSerializerV2 from '../model/ConstantsSerializerV2';

/**
* Constants service.
* @module api/ConstantsApi
* @version 2.0.0
*/
export default class ConstantsApi {

    /**
    * Constructs a new ConstantsApi. 
    * @alias module:api/ConstantsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the viewConstants operation.
     * @callback module:api/ConstantsApi~viewConstantsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ConstantsSerializerV2} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get constants.
     * @param {module:api/ConstantsApi~viewConstantsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ConstantsSerializerV2}
     */
    viewConstants(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['cookieAuth', 'tokenAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ConstantsSerializerV2;
      return this.apiClient.callApi(
        '/api/v2/constants/view_constants/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
