- name: Install Certbot
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    install_recommends: no
    update_cache: yes

- name: Generate DH parameters
  shell:
    cmd: "openssl dhparam -out /etc/letsencrypt/ssl-dhparams.pem 2048"
    creates: /etc/letsencrypt/ssl-dhparams.pem
  when: letsencrypt_email is defined

- name: Install Nginx
  apt:
    name: nginx
    install_recommends: no
    update_cache: yes

- name: Set Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Reload Nginx

- name: Disable Nginx default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - Reload Nginx

- name: Override certbot service to authenticate via nginx
  template:
    src: certbot.service
    dest: /lib/systemd/system/certbot.service
  notify:
    # Make sure that systemd reloads any changes
    - Reload Nginx

- name: Copy Maintenance directory
  copy:
    src: maintenance/
    dest: /srv/maintenance
    owner: www-data
    group: www-data

- meta: flush_handlers
