from solidago import *
from solidago.poll.scoring.user_models import *


poll = Poll(
    Users([
        ("alice",   True,   True), 
        ("bob",     True,   False), 
        ("charlie", True,   True), 
        ("dave",    True,   True), 
        ("erin",    True,   False),
        ("felix",   False,  False),
        ("grace",   True,   False),
        ("hank",    True,   False),
    ], columns=["name", "trustworthy", "pretrust"]),
    Entities([
        ("apple",     ("alice",),         (),                 0), 
        ("banana",    ("alice", "bob"),   ("charlie",),       2), 
        ("coconut",   ("alice",),         ("bob",),           11), 
        ("durian",    ("felix",),         (),                 16), 
        ("etrog",     ("dave", "erin"),   (),                 24), 
        ("fig",       ("hank",),          ("alice", "bob"),   30), 
        ("grape",     (),                 ("hank",),          36), 
        ("hazelnut",  ("erin", "hank"),   ("alice",),         43), 
        ("imbe",      ("alice",),         (),                 48), 
        ("jackfruit", ("bob", "dave"),    (),                 57),
    ], columns=["name", "authors", "mentions", "timestamp"]),
    Socials([
        ("alice",   "bob",      "vouch",    1.,     15),
        ("alice",   "bob",      "follow",   1.5,    15),
        ("alice",   "charlie",  "follow",   1.,     30),
        ("alice",   "dave",     "follow",   1.,     31),
        ("alice",   "erin",     "vouch",    1.,     33),
        ("alice",   "felix",    "follow",   .8,     35),
        ("alice",   "grace",    "follow",   .6,     37),
        ("bob",     "alice",    "follow",   1.,     25),
        ("bob",     "erin",     "vouch",    1.,     32),
        ("bob",     "erin",     "follow",   1.,     32),
        ("bob",     "felix",    "follow",   .5,     35),
        ("charlie", "alice",    "follow",   .8,     24),
        ("charlie", "bob",      "vouch",    1.,     13),
        ("charlie", "bob",      "follow",   .8,     14),
        ("charlie", "dave",     "follow",   .8,     24),
        ("charlie", "hank",     "follow",   1.,     27),
        ("dave",    "alice",    "follow",   1.,     13),
        ("dave",    "bob",      "vouch",    1.,     17),
        ("dave",    "grace",    "vouch",    1.,     23),
        ("dave",    "hank",     "vouch",    1.,     25),
        ("felix",   "alice",    "vouch",    1.,     41),
        ("felix",   "alice",    "follow",    1.,    42),
        ("felix",   "bob",      "vouch",    1.,     43),
        ("felix",   "charlie",  "vouch",    1.,     44),
        ("felix",   "charlie",  "follow",   1.,     45),
        ("felix",   "dave",     "vouch",    1.,     47),
        ("felix",   "dave",     "follow",   1.,     48),
        ("felix",   "erin",     "vouch",    1.,     50),
        ("felix",   "grace",    "vouch",    1.,     51),
        ("felix",   "hank",     "vouch",    1.,     54),
        ("grace",   "alice",    "follow",   1.,     42),
        ("grace",   "hank",     "vouch",    1.,     47),
        ("grace",   "hank",     "follow",   1.,     49),
        ("hank",    "alice",    "follow",   1.,     47),
        ("hank",    "grace",    "vouch",    1.,     51),
        ("hank",    "grace",    "follow",   1.,     53),
    ], columns=["by", "to", "kind", "weight", "timestamp"]),
    PublicSettings([
        ("alice",   "etrog",  False),
        ("dave",    "durian",   False),
    ], columns=["username", "entity_name", "public"]),
    Ratings(
        [
            ("alice",   "apple",    "repost",   15),
            ("alice",   "durian",   "report",   21),
            ("alice",   "etrog",    "repost",   25),
            ("alice",   "grape",    "report",   75),
            ("alice",   "apple",    "repost",   85),
            ("bob",     "apple",    "repost",   13),
            ("bob",     "fig",      "repost",   35),
            ("bob",     "hazelnut", "repost",   58),
            ("charlie", "coconut",  "repost",   35),
            ("charlie", "jackfruit","repost",   72),
            ("dave",    "apple",    "repost",   82),
            ("erin",    "apple",    "repost",   89),
            ("felix",   "apple",    "report",   5),
            ("felix",   "banana",   "report",   15),
            ("felix",   "durian",   "repost",   18),
            ("felix",   "apple",    "report",   55),
            ("grace",   "apple",    "repost",   57),
            ("grace",   "banana",   "repost",   76),
            ("hank",    "apple",    "repost",   96),
        ], columns=["username", "entity_name", "criterion", "timestamp"]
    ) | Ratings(
        [
            ("alice",   "grape",    "main",         15,     4),
            ("bob",     "fig",      "main",         25,     5),
            ("bob",     "fig",      "reliability",  28,     4),
            ("bob",     "fig",      "importance",   32,     5),
            ("bob",     "hazelnut", "main",         35,     3),
            ("bob",     "durian",   "main",         38,     0),
            ("felix",   "apple",    "main",         42,     0),
            ("felix",   "banana",   "main",         46,     0),
            ("felix",   "coconut",  "main",         51,     0),
            ("felix",   "durian",   "main",         36,     5),
            ("felix",   "etrog",    "main",         57,     0),
            ("felix",   "fig",      "main",         58,     0),
            ("felix",   "grape",    "main",         59,     0),
            ("felix",   "hazelnut", "main",         60,     0),
            ("felix",   "imbe",     "main",         61,     0),
            ("felix",   "jackfruit","main",         62,     0),
            ("grace",   "grape",    "main",         55,     4),
            ("hank",    "grape",    "main",         45,     4),
        ], columns=["username", "entity_name", "criterion", "timestamp", "value"]
    ).add_columns(min=0, max=5),
    Comparisons(
        [
            ("alice",   "main",     "grape",    "fig",      17, 3),
            ("alice",   "main",     "coconut",  "fig",      18, 1),
            ("alice",   "main",     "coconut",  "durian",   17, -3),
            ("erin",    "main",     "apple",    "banana",   23, 1),
            ("erin",    "reliability", "apple", "banana",   24, 1),
            ("erin",    "main",     "banana",   "coconut",  25, 0),
            ("erin",    "main",     "coconut",  "durian",   26, -3),
            ("erin",    "main",     "durian",   "etrog",    28, 3),
            ("erin",    "main",     "etrog",    "fig",      29, 0),
            ("erin",    "main",     "fig",      "grape",    31, 0),
            ("erin",    "main",     "grape",    "hazelnut", 32, -2),
            ("erin",    "main",     "hazelnut", "jackfruit",33, 2),
        ], columns=["username", "criterion", "left_name", "right_name", "timestamp", "value"]
    ).add_columns(max=3),
)

poll = functions.preference_learning.PostActions()(poll)
poll.save("tests/test_poll", fmt="yaml")