- name: Set hostname
  hostname:
    name: "{{machine_name}}"

- name: Configure hosts file
  blockinfile:
    path: "{{ item }}"
    create: true
    block: |
    
      127.0.1.1    {{machine_name}} {{domain_name}} {{api_domain_name}}
  loop:
    - /etc/hosts
    - /etc/cloud/templates/hosts.debian.tmpl  # Template used by cloud-init on startup

- name: Install minimal set of packages
  apt:
    name:
      - unattended-upgrades
      - apt-transport-https
      - ca-certificates
      - curl
      - wget
      - man-db
      - htop
      - net-tools
      - dnsutils
      - python3
      - python3-debian    # required by deb822_repository tasks in Ansible
      - python3-pip       # required by pip tasks in Ansible
      - python3-psycopg2  # required by postgresql_* tasks in Ansible
      - git
      - build-essential
      - vim
      - kitty-terminfo
      - unzip
      - gpg
      - gpg-agent
      - rsync
      - jq  # used at deploy time by get-vm-secrets
    install_recommends: no
    cache_valid_time: 3600
