# Generated by Django 3.2.3 on 2021-06-15 18:46

import core.utils.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='public_experts',
            field=core.utils.models.ComputedJsonField(compute_from='get_certified_top_raters_list', default=list, editable=False, help_text='Top 10 certified public contributor usernames'),
        ),
    ]
