# Generated by Django 3.2.3 on 2021-06-22 18:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

from settings.settings import CRITERIAS


def fill_scores_from_old_models(apps, schema_editor):
    Video = apps.get_model("tournesol", "Video")
    VideoCriteriaScore = apps.get_model("tournesol", "VideoCriteriaScore")
    ContributorRating = apps.get_model("tournesol", "ContributorRating")
    ContributorRatingCriteriaScore = apps.get_model("tournesol", "ContributorRatingCriteriaScore")
    Comparison = apps.get_model("tournesol", "Comparison")
    ComparisonCriteriaScore = apps.get_model("tournesol", "ComparisonCriteriaScore")
    
    VideoCriteriaScore.objects.bulk_create([
        VideoCriteriaScore(
            video=video,
            criteria=criteria,
            score=getattr(video, criteria),
            uncertainty=getattr(video, f"{criteria}_uncertainty"),
            quantile=getattr(video, f"{criteria}_quantile", 1.0),
        )
        for video in Video.objects.all()
        for criteria in CRITERIAS
    ])

    ContributorRatingCriteriaScore.objects.bulk_create([
        ContributorRatingCriteriaScore(
            rating=rating,
            criteria=criteria,
            score=getattr(rating, criteria),
            uncertainty=getattr(rating, f"{criteria}_uncertainty"),
        )
        for rating in ContributorRating.objects.all()
        for criteria in CRITERIAS
    ])

    ComparisonCriteriaScore.objects.bulk_create([
        ComparisonCriteriaScore(
            comparison=comparison,
            criteria=criteria,
            score=getattr(comparison, criteria),
            weight=getattr(comparison, f"{criteria}_weight"),
        )
        for comparison in Comparison.objects.all()
        for criteria in CRITERIAS
        if getattr(comparison, criteria, None) is not None
    ])


class Migration(migrations.Migration):
    """
    This migration has three phases:
        1. creates new models
        2. migrate data to new models
        3. delete old models
    """

    dependencies = [
        ('core', '0003_auto_20210615_1846'),
        ('tournesol', '0004_rename_expert_rating'),
    ]

    operations = [

        # PHASE 1: creat new models

        migrations.RenameModel(
            old_name='ContributorVideoRating',
            new_name='ContributorRating',
        ),
        migrations.CreateModel(
            name='VideoCriteriaScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.TextField(help_text='Name of the criteria', max_length=32)),
                ('score', models.FloatField(default=0, help_text='Score of the given criteria')),
                ('uncertainty', models.FloatField(default=0, help_text="Uncertainty about the video's score for the given criteria")),
                ('quantile', models.FloatField(default=1.0, help_text='Top quantile for all rated videos for aggregated scores for the given criteria. 0.0=best, 1.0=worst', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('video', models.ForeignKey(help_text='Foreign key to the video', on_delete=django.db.models.deletion.CASCADE, related_name='criteria_scores', to='tournesol.video')),
            ],
            options={
                'unique_together': {('video', 'criteria')},
            },
        ),
        migrations.CreateModel(
            name='ContributorRatingCriteriaScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.TextField(help_text='Name of the criteria', max_length=32)),
                ('score', models.FloatField(default=0, help_text='Score for the given criteria')),
                ('uncertainty', models.FloatField(default=0, help_text="Uncertainty about the video's score for the given criteria")),
                ('contributor_rating', models.ForeignKey(help_text="Foreign key to the contributor's rating", on_delete=django.db.models.deletion.CASCADE, related_name='criteria_scores', to='tournesol.contributorrating')),
            ],
            options={
                'unique_together': {('contributor_rating', 'criteria')},
            },
        ),
        migrations.CreateModel(
            name='ComparisonCriteriaScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.TextField(help_text='Name of the criteria', max_length=32)),
                ('score', models.FloatField(default=0, help_text='Score for the given comparison')),
                ('weight', models.FloatField(default=0, help_text='Weight of the comparison')),
                ('comparison', models.ForeignKey(help_text="Foreign key to the contributor's comparison", on_delete=django.db.models.deletion.CASCADE, related_name='criteria_scores', to='tournesol.comparison')),
            ],
            options={
                'unique_together': {('comparison', 'criteria')},
            },
        ),

        # PHASE 2: migrate data

        migrations.RunPython(fill_scores_from_old_models),

        # PHASE 3: delete old fields

        migrations.RemoveField(
            model_name='comparison',
            name='backfire_risk',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='backfire_risk_weight',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='better_habits',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='better_habits_weight',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='diversity_inclusion',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='diversity_inclusion_weight',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='engaging',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='engaging_weight',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='entertaining_relaxing',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='entertaining_relaxing_weight',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='importance',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='importance_weight',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='largely_recommended',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='largely_recommended_weight',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='layman_friendly',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='layman_friendly_weight',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='pedagogy',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='pedagogy_weight',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='reliability',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='reliability_weight',
        ),
        migrations.RemoveField(
            model_name='contributorrating',
            name='backfire_risk',
        ),
        migrations.RemoveField(
            model_name='contributorrating',
            name='backfire_risk_uncertainty',
        ),
        migrations.RemoveField(
            model_name='contributorrating',
            name='better_habits',
        ),
        migrations.RemoveField(
            model_name='contributorrating',
            name='better_habits_uncertainty',
        ),
        migrations.RemoveField(
            model_name='contributorrating',
            name='diversity_inclusion',
        ),
        migrations.RemoveField(
            model_name='contributorrating',
            name='diversity_inclusion_uncertainty',
        ),
        migrations.RemoveField(
            model_name='contributorrating',
            name='engaging',
        ),
        migrations.RemoveField(
            model_name='contributorrating',
            name='engaging_uncertainty',
        ),
        migrations.RemoveField(
            model_name='contributorrating',
            name='entertaining_relaxing',
        ),
        migrations.RemoveField(
            model_name='contributorrating',
            name='entertaining_relaxing_uncertainty',
        ),
        migrations.RemoveField(
            model_name='contributorrating',
            name='importance',
        ),
        migrations.RemoveField(
            model_name='contributorrating',
            name='importance_uncertainty',
        ),
        migrations.RemoveField(
            model_name='contributorrating',
            name='largely_recommended',
        ),
        migrations.RemoveField(
            model_name='contributorrating',
            name='largely_recommended_uncertainty',
        ),
        migrations.RemoveField(
            model_name='contributorrating',
            name='layman_friendly',
        ),
        migrations.RemoveField(
            model_name='contributorrating',
            name='layman_friendly_uncertainty',
        ),
        migrations.RemoveField(
            model_name='contributorrating',
            name='pedagogy',
        ),
        migrations.RemoveField(
            model_name='contributorrating',
            name='pedagogy_uncertainty',
        ),
        migrations.RemoveField(
            model_name='contributorrating',
            name='reliability',
        ),
        migrations.RemoveField(
            model_name='contributorrating',
            name='reliability_uncertainty',
        ),
        migrations.RemoveField(
            model_name='video',
            name='backfire_risk',
        ),
        migrations.RemoveField(
            model_name='video',
            name='backfire_risk_quantile',
        ),
        migrations.RemoveField(
            model_name='video',
            name='backfire_risk_uncertainty',
        ),
        migrations.RemoveField(
            model_name='video',
            name='better_habits',
        ),
        migrations.RemoveField(
            model_name='video',
            name='better_habits_quantile',
        ),
        migrations.RemoveField(
            model_name='video',
            name='better_habits_uncertainty',
        ),
        migrations.RemoveField(
            model_name='video',
            name='diversity_inclusion',
        ),
        migrations.RemoveField(
            model_name='video',
            name='diversity_inclusion_quantile',
        ),
        migrations.RemoveField(
            model_name='video',
            name='diversity_inclusion_uncertainty',
        ),
        migrations.RemoveField(
            model_name='video',
            name='engaging',
        ),
        migrations.RemoveField(
            model_name='video',
            name='engaging_quantile',
        ),
        migrations.RemoveField(
            model_name='video',
            name='engaging_uncertainty',
        ),
        migrations.RemoveField(
            model_name='video',
            name='entertaining_relaxing',
        ),
        migrations.RemoveField(
            model_name='video',
            name='entertaining_relaxing_quantile',
        ),
        migrations.RemoveField(
            model_name='video',
            name='entertaining_relaxing_uncertainty',
        ),
        migrations.RemoveField(
            model_name='video',
            name='importance',
        ),
        migrations.RemoveField(
            model_name='video',
            name='importance_quantile',
        ),
        migrations.RemoveField(
            model_name='video',
            name='importance_uncertainty',
        ),
        migrations.RemoveField(
            model_name='video',
            name='largely_recommended',
        ),
        migrations.RemoveField(
            model_name='video',
            name='largely_recommended_quantile',
        ),
        migrations.RemoveField(
            model_name='video',
            name='largely_recommended_uncertainty',
        ),
        migrations.RemoveField(
            model_name='video',
            name='layman_friendly',
        ),
        migrations.RemoveField(
            model_name='video',
            name='layman_friendly_quantile',
        ),
        migrations.RemoveField(
            model_name='video',
            name='layman_friendly_uncertainty',
        ),
        migrations.RemoveField(
            model_name='video',
            name='pedagogy',
        ),
        migrations.RemoveField(
            model_name='video',
            name='pedagogy_quantile',
        ),
        migrations.RemoveField(
            model_name='video',
            name='pedagogy_uncertainty',
        ),
        migrations.RemoveField(
            model_name='video',
            name='reliability',
        ),
        migrations.RemoveField(
            model_name='video',
            name='reliability_quantile',
        ),
        migrations.RemoveField(
            model_name='video',
            name='reliability_uncertainty',
        ),
    ]
