# Generated by Django 3.2.4 on 2021-07-20 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_userpreferences_userpreference'),
        ('tournesol', '0006_add_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='user',
            field=models.ForeignKey(help_text='Contributor (user) who left the rating', on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='core.user'),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='video_1',
            field=models.ForeignKey(help_text='Left video to compare', on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_video_1', to='tournesol.video'),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='video_2',
            field=models.ForeignKey(help_text='Right video to compare', on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_video_2', to='tournesol.video'),
        ),
    ]
