# Generated by Django 3.2.4 on 2021-08-18 20:54

import computed_property.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0007_auto_20210720_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='rating_n_ratings',
            field=computed_property.fields.ComputedIntegerField(compute_from='get_rating_n_ratings', default=0, editable=False, help_text='Total number of pairwise comparisons for this videofrom certified contributors'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(help_text='Video ID from YouTube URL, matches ^[A-Za-z0-9-_]{11}$', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9-_]{11}$', 'Video ID must match ^[A-Za-z0-9-_]{11}$')]),
        ),
        migrations.AlterField(
            model_name='videocriteriascore',
            name='quantile',
            field=models.FloatField(default=1.0, help_text='Top quantile for all rated videos for aggregated scoresfor the given criteria. 0.0=best, 1.0=worst', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
