# Generated by Django 3.2.6 on 2021-09-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0009_alter_comparisoncriteriascore_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisoncriteriascore',
            name='score',
            field=models.FloatField(help_text='Score for the given comparison'),
        ),
    ]
