# Generated by Django 3.2.6 on 2021-10-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0010_alter_comparisoncriteriascore_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='datetime_lastedit',
            field=models.DateTimeField(auto_now=True, help_text='Time the comparison was edited the last time', null=True),
        ),
    ]
