# Generated by Django 3.2.6 on 2021-10-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0011_alter_comparison_datetime_lastedit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='rating_n_contributors',
            field=models.IntegerField(default=0, help_text='Total number of certified contributors who rated the video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='rating_n_ratings',
            field=models.IntegerField(default=0, help_text='Total number of pairwise comparisons for this videofrom certified contributors'),
        ),
    ]
