# Generated by Django 3.2.6 on 2021-11-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0012_auto_20211021_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the tag', max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tournesol.Tag'),
        ),
    ]
