# Generated by Django 3.2.10 on 2021-12-28 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0014_create_all_contributor_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='is_update_pending',
        ),
        migrations.RemoveField(
            model_name='video',
            name='n_private_contributors',
        ),
        migrations.RemoveField(
            model_name='video',
            name='n_public_contributors',
        ),
        migrations.RemoveField(
            model_name='video',
            name='public_contributors',
        ),
        migrations.AlterField(
            model_name='comparisoncriteriascore',
            name='score',
            field=models.FloatField(help_text='Score for the given comparison', validators=[django.core.validators.MinValueValidator(-10.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
