# Generated by Django 3.2.11 on 2022-01-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0015_remove_obsolete_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='download_attempts',
        ),
        migrations.RemoveField(
            model_name='video',
            name='download_failed',
        ),
        migrations.AlterField(
            model_name='video',
            name='last_download_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Last time fetch of metadata was attempted', null=True),
        ),
         migrations.RenameField(
            model_name='video',
            old_name='last_download_time',
            new_name='last_metadata_request_at',
        ),
    ]
