# Generated by Django 3.2.11 on 2022-01-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0016_clean_metadata_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.BigIntegerField(blank=True, help_text='Number of views', null=True),
        ),
    ]
