# Generated by Django 3.2.11 on 2022-02-03 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0020_rename_models_related_to_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='entity',
            name='type',
            field=models.CharField(choices=[('video', 'Video')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='uid',
            field=models.CharField(help_text='A unique identifier, build with a namespace and an external id.', max_length=144, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contributorrating',
            name='video',
            field=models.ForeignKey(help_text='Entity being scored', on_delete=django.db.models.deletion.CASCADE, related_name='contributorvideoratings', to='tournesol.entity'),
        ),
    ]
