# Generated by Django 3.2.11 on 2022-02-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournesol", "0021_fill_new_entity_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="type",
            field=models.CharField(
                choices=[("video", "Video")], default="", max_length=32
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="entity",
            name="uid",
            field=models.CharField(
                default=1,
                help_text="A unique identifier, build with a namespace and an external id.",
                max_length=144,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
