# Generated by Django 4.0.2 on 2022-02-07 16:36

import computed_property.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import tournesol.models.poll
from tournesol.models.poll import DEFAULT_POLL_NAME, VideoEntity
import uuid


def create_default_poll(apps, schema_editor):
    Poll = apps.get_model("tournesol", "Poll")
    Poll.objects.get_or_create(
        name=DEFAULT_POLL_NAME,
        defaults={"entity_type": VideoEntity.name}
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournesol', '0022_entity_refactor_part2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True)),
                ('entity_type', models.CharField(choices=[('video', 'Video')], max_length=32)),
            ],
        ),
        migrations.RunPython(create_default_poll, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='comparisonsliderchanges',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comparisonsliderchanges',
            name='video_left',
        ),
        migrations.RemoveField(
            model_name='comparisonsliderchanges',
            name='video_right',
        ),
        migrations.RemoveConstraint(
            model_name='comparison',
            name='videos_cannot_be_equal',
        ),
        migrations.RenameField(
            model_name='comparison',
            old_name='video_1',
            new_name='entity_1',
        ),
        migrations.RenameField(
            model_name='comparison',
            old_name='video_2',
            new_name='entity_2',
        ),
        migrations.RenameField(
            model_name='contributorrating',
            old_name='video',
            new_name='entity',
        ),
        migrations.AlterField(
            model_name='comparison',
            name='video_1_2_ids_sorted',
            field=computed_property.fields.ComputedCharField(compute_from='entity_first_second', default=uuid.uuid1, editable=False, help_text='Sorted pair of video IDs', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='comparison',
            constraint=models.CheckConstraint(check=models.Q(('entity_1', django.db.models.expressions.F('entity_2')), _negated=True), name='videos_cannot_be_equal'),
        ),
        migrations.DeleteModel(
            name='ComparisonSliderChanges',
        ),
        migrations.AlterUniqueTogether(
            name='comparison',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='contributorrating',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='entitycriteriascore',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='comparison',
            name='poll',
            field=models.ForeignKey(default=tournesol.models.poll.Poll.default_poll_pk, on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='tournesol.poll'),
        ),
        migrations.AddField(
            model_name='contributorrating',
            name='poll',
            field=models.ForeignKey(default=tournesol.models.poll.Poll.default_poll_pk, on_delete=django.db.models.deletion.CASCADE, related_name='contributor_ratings', to='tournesol.poll'),
        ),
        migrations.AddField(
            model_name='entitycriteriascore',
            name='poll',
            field=models.ForeignKey(default=tournesol.models.poll.Poll.default_poll_pk, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='tournesol.poll'),
        ),
        migrations.AlterUniqueTogether(
            name='comparison',
            unique_together={('user', 'poll', 'video_1_2_ids_sorted')},
        ),
        migrations.AlterUniqueTogether(
            name='contributorrating',
            unique_together={('user', 'entity', 'poll')},
        ),
        migrations.AlterUniqueTogether(
            name='entitycriteriascore',
            unique_together={('video', 'poll', 'criteria')},
        ),
        migrations.RenameField(
            model_name='comparison',
            old_name='video_1_2_ids_sorted',
            new_name='entity_1_2_ids_sorted',
        ),
        migrations.AlterUniqueTogether(
            name='comparison',
            unique_together={('user', 'poll', 'entity_1_2_ids_sorted')},
        ),
        migrations.RenameField(
            model_name='entitycriteriascore',
            old_name='video',
            new_name='entity',
        ),
        migrations.AlterUniqueTogether(
            name='entitycriteriascore',
            unique_together={('entity', 'poll', 'criteria')},
        ),
    ]
