# Generated by Django 3.2.11 on 2022-02-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0023_make_new_entity_fields_notnull'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoselectorskips',
            name='user',
        ),
        migrations.RemoveField(
            model_name='videoselectorskips',
            name='video',
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'entities'},
        ),
        migrations.RemoveField(
            model_name='entity',
            name='caption_text',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='info',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='pareto_optimal',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='wrong_url',
        ),
        migrations.DeleteModel(
            name='VideoRatingThankYou',
        ),
        migrations.DeleteModel(
            name='VideoSelectorSkips',
        ),
    ]
