# Generated by Django 4.0.2 on 2022-02-10 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tournesol", "0025_create_default_criterias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comparison",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comparisons",
                to="tournesol.poll",
            ),
        ),
    ]
