# Generated by Django 4.0.2 on 2022-02-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0026_remove_comparison_poll_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
