# Generated by Django 4.0.2 on 2022-02-22 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournesol", "0027_alter_entity_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributorrating",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributor_ratings",
                to="tournesol.poll",
            ),
        ),
    ]
