# Generated by Django 4.0.2 on 2022-02-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0027_alter_entity_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='tournesol_score',
            field=models.FloatField(default=0, help_text='Tournesol ScoreCalculated from the criteria_score from certified contributors'),
        ),
    ]
