# Generated by Django 4.0.2 on 2022-02-23 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0029_populate_video_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='is_unlisted',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='language',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='name',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='uploader',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='video_id',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='views',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
