# Generated by Django 4.0.3 on 2022-03-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournesol", "0030_remove_entity_description_remove_entity_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="tournesol_score",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="The aggregated of all criteria for all users in a specific poll.",
                null=True,
            ),
        ),
    ]
