# Generated by Django 4.0.2 on 2022-03-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0030_remove_entity_description_remove_entity_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('2022_candidate', 'Candidate (FR 2022)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='poll',
            name='entity_type',
            field=models.CharField(choices=[('video', 'Video'), ('2022_candidate', 'Candidate (FR 2022)')], max_length=32),
        ),
    ]
