# Generated by Django 4.0.3 on 2022-03-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0033_add_poll_presidentielle2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='algorithm',
            field=models.CharField(choices=[('licchavi', 'Licchavi'), ('mehestan', 'Mehestan')], default='licchavi', max_length=32),
        ),
    ]
