# Generated by Django 4.0.3 on 2022-04-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0035_alter_comparison_entity_1_alter_comparison_entity_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitycriteriascore',
            name='deviation',
            field=models.FloatField(blank=True, default=None, help_text="A measure of deviation between the individual scores and the global 'score'. May also be understood as a measure of polarization", null=True),
        ),
    ]
