# Generated by Django 4.0.3 on 2022-04-22 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournesol', '0036_entitycriteriascore_deviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorScaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.TextField(db_index=True, help_text='Name of the criteria', max_length=32)),
                ('scale', models.FloatField(default=1, help_text="Scaling factor, often denoted 's'")),
                ('scale_uncertainty', models.FloatField(blank=True, default=None, help_text='Scaling factor uncertainty', null=True)),
                ('translation', models.FloatField(default=0, help_text="Scaling translation, often denoted 'tau'")),
                ('translation_uncertainty', models.FloatField(blank=True, default=None, help_text='Translation uncertainty', null=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_scalings', to='tournesol.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scalings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('poll', 'criteria', 'user')},
            },
        ),
    ]
