# Generated by Django 4.0.3 on 2022-04-29 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0037_contributorscaling'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entitycriteriascore',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='entitycriteriascore',
            name='score_mode',
            field=models.CharField(choices=[('default', 'Default'), ('all_equal', 'All Equal'), ('trusted_only', 'Trusted Only')], default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='entitycriteriascore',
            name='entity',
            field=models.ForeignKey(help_text='Foreign key to the video', on_delete=django.db.models.deletion.CASCADE, related_name='all_criteria_scores', to='tournesol.entity'),
        ),
        migrations.AlterUniqueTogether(
            name='entitycriteriascore',
            unique_together={('entity', 'poll', 'criteria', 'score_mode')},
        ),
    ]
