# Generated by Django 4.0.4 on 2022-05-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0038_fix_metadata_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
