# Generated by Django 4.0.4 on 2022-05-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournesol", "0039_poll_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="On an inactive poll, entity scores are not updated and comparisons can't be created, updated or deleted by users.",
            ),
        ),
    ]
