# Generated by Django 4.0.4 on 2022-06-13 14:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournesol', '0040_alter_poll_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoRateLater',
            new_name='RateLater',
        ),
    ]
