# Generated by Django 4.0.4 on 2022-06-18 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tournesol.models.poll


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournesol', '0041_rename_videoratelater_ratelater'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratelater',
            options={'ordering': ['user', '-created_at']},
        ),
        migrations.RenameField(
            model_name='ratelater',
            old_name='datetime_add',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='ratelater',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ratelater',
            name='poll',
            field=models.ForeignKey(blank=True, default=tournesol.models.poll.Poll.default_poll_pk, help_text='Poll associated with the entity to rate later', on_delete=django.db.models.deletion.CASCADE, related_name='ratelaters', to='tournesol.poll'),
        ),
        migrations.AlterField(
            model_name='ratelater',
            name='user',
            field=models.ForeignKey(help_text='Person who saves the video', on_delete=django.db.models.deletion.CASCADE, related_name='ratelaters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ratelater',
            name='video',
            field=models.ForeignKey(help_text='Entity in the rate later list', on_delete=django.db.models.deletion.CASCADE, related_name='ratelaters', to='tournesol.entity'),
        ),
        migrations.AlterUniqueTogether(
            name='ratelater',
            unique_together={('poll', 'user', 'video')},
        ),
    ]
