# Generated by Django 4.0.4 on 2022-06-20 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournesol', '0041_rename_videoratelater_ratelater'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='scale',
            field=models.FloatField(default=1.0, help_text='Scale factor to apply on scores (applied only for Mehestan)'),
        ),
        migrations.AddField(
            model_name='poll',
            name='translation',
            field=models.FloatField(default=0.0, help_text='Offset value to apply on scores (applied only for Mehestan)'),
        ),
        migrations.AlterField(
            model_name='ratelater',
            name='user',
            field=models.ForeignKey(help_text='Person who saves the video', on_delete=django.db.models.deletion.CASCADE, related_name='ratelaters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ratelater',
            name='video',
            field=models.ForeignKey(help_text='Video in the rate later list', on_delete=django.db.models.deletion.CASCADE, related_name='ratelaters', to='tournesol.entity'),
        ),
    ]
