# Generated by Django 4.0.4 on 2022-06-29 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournesol', '0041_rename_videoratelater_ratelater'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributorratingcriteriascore',
            name='raw_score',
            field=models.FloatField(default=0, help_text='Computed individual score without any scaling applied'),
        ),
        migrations.AddField(
            model_name='contributorratingcriteriascore',
            name='raw_uncertainty',
            field=models.FloatField(default=0, help_text='Computed individual uncertainty without any scaling applied'),
        ),
        migrations.AddField(
            model_name='poll',
            name='sigmoid_scale',
            field=models.FloatField(default=None, help_text='Scaling factor multiplied by score before the sigmoid function is applied. Updated automatically on each run. (Mehestan only).', null=True),
        ),
        migrations.AlterField(
            model_name='contributorratingcriteriascore',
            name='score',
            field=models.FloatField(default=0, help_text='Score for the given criteria, after individual and poll scalings applied'),
        ),
        migrations.AlterField(
            model_name='contributorratingcriteriascore',
            name='uncertainty',
            field=models.FloatField(default=0, help_text='Uncertainty about the criteria score'),
        ),
        migrations.AlterField(
            model_name='ratelater',
            name='user',
            field=models.ForeignKey(help_text='Person who saves the video', on_delete=django.db.models.deletion.CASCADE, related_name='ratelaters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ratelater',
            name='video',
            field=models.ForeignKey(help_text='Video in the rate later list', on_delete=django.db.models.deletion.CASCADE, related_name='ratelaters', to='tournesol.entity'),
        ),
    ]
