# Generated by Django 4.0.4 on 2022-06-12 12:41

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations
from tournesol.entities.base import EntityType
from tournesol.utils.video_language import POSTGRES_LANGUAGES
from django.contrib.postgres.operations import UnaccentExtension

def migrate_forward(apps, schema_editor):
    """
    Fill the search vector, used for fast full-text search
    """
    EntityType.build_all_search_vectors()

class Migration(migrations.Migration):
    dependencies = [
        ("tournesol", "0042_contributorratingcriteriascore_raw_score_and_more"),
    ]

    # Create new Postgres full-text search configs using the Unaccent dictionary
    create_customized_configs = [
        migrations.RunSQL(f"""
        CREATE TEXT SEARCH CONFIGURATION customized_{language}( COPY = {language} );
        ALTER TEXT SEARCH CONFIGURATION customized_{language}
        ALTER MAPPING FOR hword, hword_part, word
        WITH unaccent, {language}_stem;
        """)
        for language in POSTGRES_LANGUAGES
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['search_vector'],
                name='search_index'
            ),
        ),
        UnaccentExtension(),
    ] + create_customized_configs + [
        migrations.RunPython(migrate_forward, migrations.RunPython.noop),
    ]
