# Generated by Django 4.0.4 on 2022-06-18 14:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournesol', '0042_alter_ratelater_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratelater',
            old_name='video',
            new_name='entity',
        ),
        migrations.AlterUniqueTogether(
            name='ratelater',
            unique_together={('poll', 'user', 'entity')},
        ),
    ]
