# Generated by Django 4.0.6 on 2022-08-02 13:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournesol", "0044_alter_ratelater_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratelater",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Time at which the video is saved.",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ratelater",
            name="poll",
            field=models.ForeignKey(
                help_text="The poll in which the user is saving the entity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratelaters",
                to="tournesol.poll",
            ),
        ),
    ]
