# Generated by Django 4.0.7 on 2022-09-01 14:21

import django.db.models.deletion
from django.db import migrations, models

import tournesol.models.poll


class Migration(migrations.Migration):

    dependencies = [
        ("tournesol", "0046_search_config_and_vector"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityPollRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tournesol_score",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text="The aggregated score of the main criterion for all users, in a specific poll.",
                        null=True,
                    ),
                ),
                (
                    "n_comparisons",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of pairwise comparisons for this entityfrom certified contributors",
                    ),
                ),
                (
                    "n_contributors",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of certified contributors who rated the entity",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="all_poll_ratings",
                        to="tournesol.entity",
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        default=tournesol.models.poll.Poll.default_poll_pk,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="all_entity_ratings",
                        to="tournesol.poll",
                    ),
                ),
            ],
        ),
    ]
