"""
Migration used to define model entity_poll_rating
"""
# Generated by Django 4.0.6 on 2022-08-18 08:36

import django.db.models.deletion
from django.db import migrations, models

import tournesol.models.poll


class Migration(migrations.Migration):
    """
    Migration used to define model entity_poll_rating
    """

    dependencies = [
        ('tournesol', '0046_search_config_and_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityPollRating',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')
                 ),
                ('entity_score',
                 models.FloatField(
                     blank=True,
                     default=None,
                     help_text='The aggregated of all criteria for all users in a specific poll.',
                     null=True)
                 ),
                ('n_comparisons',
                 models.IntegerField(
                     default=0,
                     help_text='Total number of comparisons for this entity from contributors')
                 ),
                ('n_contributors',
                 models.IntegerField(
                     default=0,
                     help_text='Total number of certified contributors who rated the entity')
                 ),
                ('entity',
                 models.ForeignKey(
                     help_text='Foreign key to the entity',
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='all_poll_ratings',
                     to='tournesol.entity')
                 ),
                ('poll',
                 models.ForeignKey(
                     default=tournesol.models.poll.Poll.default_poll_pk,
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='ratings',
                     to='tournesol.poll')
                 ),
            ],
        ),
    ]
