# Generated by Django 4.0.7 on 2022-09-15 20:06

from django.db import migrations, models

def migrate_forward(apps, schema_editor):
    """
    Replace legacy Licchavi with Mehestan
    """
    Poll = apps.get_model("tournesol", "Poll")
    Poll.objects.update(algorithm="mehestan")

class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0047_entitypollrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='algorithm',
            field=models.CharField(choices=[('licchavi', 'Licchavi'), ('mehestan', 'Mehestan')], default='mehestan', max_length=32),
        ),
        migrations.RunPython(
            migrate_forward,
            migrations.RunPython.noop,
        )
    ]
