# Generated by Django 4.0.3 on 2022-11-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0048_alter_poll_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributorratingcriteriascore',
            name='voting_right',
            field=models.FloatField(default=0, help_text='Voting right computed based on trust scores and contributors having rated the entity on the criteria'),
        ),
    ]
