# Generated by Django 4.0.8 on 2022-10-31 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournesol", "0049_contributorratingcriteriascore_voting_right"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="entitypollrating",
            unique_together={("poll", "entity")},
        ),
    ]
