# Generated by Django 4.1.9 on 2023-06-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0052_alter_entity_last_metadata_request_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitypollrating',
            name='sum_trust_scores',
            field=models.FloatField(default=0.0, help_text='Sum of trust scores of the contributors who rated the entity'),
        ),
    ]
