# Generated by Django 4.1.7 on 2023-08-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournesol", "0053_entitypollrating_sum_trust_scores"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entitycriteriascore",
            name="quantile",
        ),
        migrations.RemoveField(
            model_name="poll",
            name="sigmoid_scale",
        ),
    ]
