# Generated by Django 4.2.7 on 2023-11-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournesol", "0057_entitycontext_entitycontextlocale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entitycontext",
            name="origin",
            field=models.CharField(
                choices=[("ASSOCIATION", "Association"), ("CONTRIBUTORS", "Contributors")],
                default="ASSOCIATION",
                help_text="The persons who want to share this context with the rest of the community.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="entitycontext",
            name="predicate",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="A JSON object. The keys/values should match the metadata keys/values of the targeted entities.",
            ),
        ),
    ]
