# Generated by Django 4.2.7 on 2023-11-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournesol", "0058_alter_entitycontext_origin_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entitycontextlocale",
            name="source_label",
        ),
        migrations.RemoveField(
            model_name="entitycontextlocale",
            name="source_url",
        ),
    ]
