# Generated by Django 4.2.11 on 2024-05-02 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournesol", "0060_remove_entity_tournesol_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="comparisoncriteriascore",
            name="score_max",
            field=models.IntegerField(
                default=10,
                help_text="The absolute value of the maximum score.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comparisoncriteriascore",
            name="score",
            field=models.FloatField(help_text="Score for the given comparison"),
        ),
    ]
