# Generated by Django 4.2.19 on 2025-08-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournesol", "0061_comparisoncriteriascore_score_max_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributorrating",
            name="entity_seen",
            field=models.BooleanField(
                default=False,
                help_text="Has the user already seen, or read, or understood the entity?",
            ),
        ),
    ]
