# Generated by Django 4.2.19 on 2025-08-08 08:34

from django.db import migrations
from django.db.models import FilteredRelation, F, Q, Count


def mark_compared_entities_as_seen(apps, schema_editor):
    """
    Mark all compared entities as "seen" by the users.
    """

    ratings_to_update = []

    ContributorRating = apps.get_model("tournesol", "ContributorRating")
    ratings_iterator = (
        ContributorRating.objects.annotate(
            related_comparisons=FilteredRelation(
                "user__comparisons",
                condition=(
                    Q(user__comparisons__poll=F("poll"))
                    & (
                        Q(user__comparisons__entity_1=F("entity"))
                        | Q(user__comparisons__entity_2=F("entity"))
                    )
                ),
            )
        )
        .annotate(n_comparisons=Count("related_comparisons"))
        .iterator()
    )

    for rating in ratings_iterator:
        if rating.n_comparisons > 0:
            rating.entity_seen = True
            ratings_to_update.append(rating)

    ContributorRating.objects.bulk_update(
        ratings_to_update,
        ["entity_seen"],
        batch_size=2000,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("tournesol", "0062_contributorrating_entity_seen"),
    ]

    operations = [
        migrations.RunPython(
            code=mark_compared_entities_as_seen, reverse_code=migrations.RunPython.noop
        ),
    ]
