# Generated by Django 4.2 on 2026-03-26

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournesol", "0063_data_mark_compared_entities_as_seen"),
    ]

    operations = [
        TrigramExtension(),
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS entity_metadata_name_trgm
            ON tournesol_entity
            USING gin ((metadata->>'name') gin_trgm_ops);
            """,
            reverse_sql="DROP INDEX IF EXISTS entity_metadata_name_trgm;",
        ),
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS entity_metadata_uploader_trgm
            ON tournesol_entity
            USING gin ((metadata->>'uploader') gin_trgm_ops);
            """,
            reverse_sql="DROP INDEX IF EXISTS entity_metadata_uploader_trgm;",
        ),
    ]
