# Generated by Django 5.2.17 on 2026-10-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0065_alter_criterialocale_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitysource',
            name='last_metadata_request_at',
            field=models.DateTimeField(blank=True, help_text='Last time fetch of metadata was attempted', null=True),
        ),
        migrations.AddField(
            model_name='entitysource',
            name='metadata_timestamp',
            field=models.DateTimeField(blank=True, help_text='Timestamp the metadata was updated', null=True),
        ),
    ]
