# Generated by Django 3.2.3 on 2021-07-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0005_add_criteria_score_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisoncriteriascore',
            name='criteria',
            field=models.TextField(db_index=True, help_text='Name of the criteria', max_length=32),
        ),
        migrations.AlterField(
            model_name='contributorratingcriteriascore',
            name='criteria',
            field=models.TextField(db_index=True, help_text='Name of the criteria', max_length=32),
        ),
        migrations.AlterField(
            model_name='videocriteriascore',
            name='criteria',
            field=models.TextField(db_index=True, help_text='Name of the criteria', max_length=32),
        ),
    ]
