# Generated by Django 3.2.6 on 2021-09-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0008_auto_20210818_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisoncriteriascore',
            name='weight',
            field=models.FloatField(default=1, help_text='Weight of the comparison'),
        ),
    ]
