version: "3.3"
   
services:
  db:
    container_name: tournesol-dev-db
    image: postgres:buster
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tournesol
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    expose:
      - "5432"
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      tournesol-dev: {}

  api:
    build: .
    container_name: tournesol-dev-api
    command: 
        - wait-for-it
        - db:5432
        - --
        - bash
        - -c
        - "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./code:/code
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      tournesol-dev: {}
    depends_on:
      - db

networks:
  tournesol-dev:
    # name: tournesol-dev # requires specification version >= 3.5
