# Generated by Django 4.0.4 on 2022-05-03 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='vouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False, help_text='Should the vouching be public?')),
                ('trust_value', models.FloatField(default=0, help_text='trust value assigned by vouchinguser to vouchedforuser')),
                ('uncertainty', models.FloatField(default=0, help_text='Uncertainty about the vouching score')),
                ('criteria', models.TextField(db_index=True, default=0, help_text='Name of the properity on which the vouching is based', max_length=32)),
                ('vouchedfor', models.ForeignKey(help_text='The contributor', on_delete=django.db.models.deletion.CASCADE, related_name='vouchedforuser', to=settings.AUTH_USER_MODEL)),
                ('vouching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchinguser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
