# Generated by Django 4.0.4 on 2022-05-04 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vouch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouch',
            name='vouchedfor',
        ),
        migrations.RemoveField(
            model_name='vouch',
            name='vouching',
        ),
        migrations.AddField(
            model_name='vouch',
            name='by',
            field=models.ForeignKey(default=0, help_text='User who vouch for', on_delete=django.db.models.deletion.CASCADE, related_name='user_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vouch',
            name='to',
            field=models.ForeignKey(default=0, help_text='User being vouched for', on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vouch',
            name='trust_value',
            field=models.FloatField(default=0, help_text='Trust value assigned by vouching user to vouched-for user.'),
        ),
    ]
