# Generated by Django 4.0.6 on 2022-07-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vouch", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voucher",
            name="trust_value",
        ),
        migrations.AddField(
            model_name="voucher",
            name="vouch_value",
            field=models.FloatField(
                default=0,
                help_text="The vouch value given by the vouching user to receiving user.",
            ),
        ),
    ]
