# Generated by Django 4.0.7 on 2022-09-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouch', '0003_alter_voucher_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Should the voucher be public?'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='value',
            field=models.FloatField(default=1, help_text='The vouch value given by the vouching user to receiving user.'),
        ),
    ]
