# Generated by Django 4.0.4 on 2022-05-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouch', '0003_voucher_delete_vouch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='uncertainty',
        ),
    ]
