# Plausible Analytics
#
# This playbook installs a self-hosted instance of Plausible Analytics.
# See the documentation: https://plausible.io/docs/self-hosting
#
# This playbook requires the following apt packages:
#   - certbot
#   - python3-certbot-nginx
#   - nginx
#   - docker-ce
#   - docker-ce-cli
#   - containerd.io
#   - docker-compose-plugin

#
# Install the systemd unit
#

- name: Copy tournesol-website-analytics service
  template:
    dest: /etc/systemd/system/tournesol-website-analytics.service
    src: tournesol-website-analytics.service.j2

- name: Enable and start tournesol-website-analytics service
  systemd:
    name: tournesol-website-analytics.service
    state: started
    enabled: yes
    daemon_reload: yes

#
# Install the TLS certificates
#

- name: Check if website analytics certificates are already present
  stat:
    path: /etc/letsencrypt/live/{{website_analytics_domain_name}}/fullchain.pem
  register: website_analytics_cert_file
  when: letsencrypt_email is defined

- name: Stop NGINX if website analytics certificates are not present
  systemd:
    name: nginx
    state: stopped
  when: letsencrypt_email is defined and website_analytics_cert_file.stat.exists == False

- name: Run Certbot for website analytics domain
  shell:
    cmd: "certbot certonly --standalone -d {{website_analytics_domain_name}} -n --agree-tos -m {{letsencrypt_email}}"
    creates: /etc/letsencrypt/live/{{website_analytics_domain_name}}/fullchain.pem
  when: letsencrypt_email is defined

#
# Install the NGINX configuration
#

- name: Copy NGINX configuration
  template:
    src: website_analytics.j2
    dest: /etc/nginx/sites-available/website_analytics
  notify:
    - Reload Nginx

- name: Enable NGINX configuration
  file:
    src: /etc/nginx/sites-available/website_analytics
    dest: /etc/nginx/sites-enabled/website_analytics
    state: link
  notify: Reload Nginx

- meta: flush_handlers
