# users appearing here should also have a (possibly empty) roles/users/files/admin-users/<user_name> directory
# SSH keys can be put here (as `ssh_public_key`) or into roles/users/files/admin-users/<user_name>/.ssh/authorized_keys
admin_users:
  - name: jst
    shell: "/usr/bin/zsh"
    state: absent
    delete_home: yes

  - name: louisfaucon
    shell: "/usr/bin/zsh"

  - name: lenhoang
    shell: "/usr/bin/zsh"
    state: absent
    delete_home: yes

  - name: adrien
    shell: "/usr/bin/zsh"

  - name: oizo
    shell: "/usr/bin/zsh"

  - name: aidan
    shell: "/usr/bin/zsh"
    state: absent
    delete_home: yes
