# Generated by Django 4.0.7 on 2022-09-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faqanswerlocale",
            options={"verbose_name": "FAQ Answer Locale"},
        ),
        migrations.AlterModelOptions(
            name="faquestion",
            options={"ordering": ["rank"], "verbose_name": "FAQ Question"},
        ),
        migrations.AddField(
            model_name="faquestion",
            name="enabled",
            field=models.BooleanField(
                default=True,
                help_text="Disabled questions shouldn't be displayed by the API.",
            ),
        ),
    ]
