# Generated by Django 4.0.7 on 2022-09-26 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0002_alter_faqanswerlocale_question"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FAQuestion",
            new_name="FAQEntry",
        ),
        migrations.AlterField(
            model_name="faquestionlocale",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="faq.faqentry",
            ),
        ),
    ]
