# Generated by Django 4.1.10 on 2023-07-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_alter_faqentry_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faqanswerlocale',
            table='backoffice_faqanswerlocale',
        ),
        migrations.AlterModelTable(
            name='faqentry',
            table='backoffice_faqentry',
        ),
        migrations.AlterModelTable(
            name='faquestionlocale',
            table='backoffice_faquestionlocale',
        ),
    ]
