# Generated by Django 4.1.10 on 2023-07-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0005_alter_models_tables_names"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="faqanswerlocale",
            table="faq_faqanswerlocale",
        ),
        migrations.AlterModelTable(
            name="faqentry",
            table="faq_faqentry",
        ),
        migrations.AlterModelTable(
            name="faquestionlocale",
            table="faq_faquestionlocale",
        ),
    ]
