# Generated by Django 4.1.10 on 2023-07-11 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0013_move_data_from_faq_to_backoffice"),
        ("faq", "0006_reset_faq_table_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faqanswerlocale",
            options={"managed": False, "verbose_name": "FAQ Answer Locale"},
        ),
        migrations.AlterModelOptions(
            name="faqentry",
            options={
                "managed": False,
                "ordering": ["rank"],
                "verbose_name": "FAQ Entry",
                "verbose_name_plural": "FAQ Entries",
            },
        ),
        migrations.AlterModelOptions(
            name="faquestionlocale",
            options={"managed": False, "verbose_name": "FAQ Question Locale"},
        ),
    ]
