# Generated by Django 4.1.10 on 2023-08-28 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0007_make_faq_unmanaged"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="faquestionlocale",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="faquestionlocale",
            name="question",
        ),
        migrations.DeleteModel(
            name="FAQAnswerLocale",
        ),
        migrations.DeleteModel(
            name="FAQEntry",
        ),
        migrations.DeleteModel(
            name="FAQuestionLocale",
        ),
    ]
