version: "3.3"
   
services:
  db:
    container_name: tournesol-dev-db
    image: postgres:buster
    user: ${DB_UID}:${DB_GID}
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tournesol
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    expose:
      - "5432"
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      tournesol-dev: {}

  api:
    build: ../backend/dev-env
    container_name: tournesol-dev-api
    environment:
      - SETTINGS_FILE=/backend/dev-env/settings-tournesol.yaml
    command: 
        - wait-for-it
        - db:5432
        - --
        - bash
        - -c
        - "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../backend:/backend
    expose:
      - "8000"
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      tournesol-dev: {}
    depends_on:
      - db

  front:
    build: ../frontend/dev-env
    container_name: tournesol-dev-front
    command:
      - bash
      - -c
      - "cd /frontend && ./scripts/generate-services-from-openapi.sh && yarn start"
    volumes:
      - ../frontend:/frontend
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      tournesol-dev: {}

networks:
  tournesol-dev:
    # name: tournesol-dev # requires specification version >= 3.5
