# Generated by Django 3.2.4 on 2021-06-06 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Expertise keyword description', max_length=100)),
                ('rank', models.IntegerField(default=0, help_text='Ordering field')),
                ('user', models.ForeignKey(help_text='User for the expertise keywords', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expertise_keywords', to='core.user')),
            ],
            options={
                'ordering': ['rank', 'name'],
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Expertise description', max_length=100)),
                ('rank', models.IntegerField(default=0, help_text='Ordering field')),
                ('user', models.ForeignKey(help_text='User for the expertise', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expertises', to='core.user')),
            ],
            options={
                'ordering': ['rank', 'name'],
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(help_text='Degree level', max_length=100)),
                ('domain', models.CharField(help_text='Degree domain', max_length=100)),
                ('institution', models.CharField(help_text='Degree institution', max_length=100)),
                ('rank', models.IntegerField(default=0, help_text='Ordering field')),
                ('user', models.ForeignKey(help_text='User that the degree belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='core.user')),
            ],
            options={
                'ordering': ['rank', 'level', 'domain', 'institution'],
                'unique_together': {('level', 'domain', 'institution', 'user')},
            },
        ),
    ]
