# Generated by Django 3.2.4 on 2021-07-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210615_1846'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPreferences',
            new_name='UserPreference',
        ),
    ]
