# Generated by Django 3.2.11 on 2022-01-24 17:44

from django.db import migrations
from django.db.models import F


def remove_email_used_as_username(apps, schema_editor):
    User = apps.get_model("core", "User")
    users_to_update = User.objects.filter(email=F("username"))
    for u in users_to_update.iterator():
        u.username = f"user{u.id:04}"
        u.save(update_fields=["username"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_email_unique_in_db'),
    ]

    operations = [
        migrations.RunPython(
            code=remove_email_used_as_username,
            reverse_code=migrations.RunPython.noop
        )
    ]
