# Generated by Django 4.0.4 on 2022-05-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_delete_userpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="trust_score",
            field=models.FloatField(
                default=None,
                help_text="The global trust score assigned to the user based on the vouching mechanism.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Self-description (other degrees, biography, ...)",
                null=True,
            ),
        ),
    ]
