# Generated by Django 4.0.4 on 2022-05-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='competencies',
            field=models.TextField(blank=True, help_text='Your competencies', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='diplomas',
            field=models.TextField(blank=True, help_text='Your diplomas', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trust_score',
            field=models.FloatField(default=0, help_text='Your trust score', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Self-description (other degrees, biography, ...)', null=True),
        ),
    ]
