# Generated by Django 4.0.4 on 2022-05-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_competencies_user_diplomas_user_trust_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='competencies',
        ),
        migrations.RemoveField(
            model_name='user',
            name='diplomas',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trust_score',
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Self-description (degree, biography, ...)', null=True),
        ),
    ]
