# Generated by Django 4.0.4 on 2022-05-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_competencies_user_diplomas_user_trust_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='competencies',
        ),
        migrations.RemoveField(
            model_name='user',
            name='diplomas',
        ),
        migrations.AlterField(
            model_name='user',
            name='trust_score',
            field=models.FloatField(default=None, help_text='The global trust score assigned to the user based on the vouching mechanism. Scale to be used as a voting weight.'),
        ),
    ]
