# Generated by Django 4.0.4 on 2022-05-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_user_competencies_remove_user_diplomas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='trust_score',
            field=models.FloatField(default=None, help_text='The global trust score assigned to the user based on the vouching mechanism', null=True),
        ),
    ]
