# Generated by Django 4.0.7 on 2022-09-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_trust_score_isnow_voting_right"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="voting_right",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="The voting right assigned to the user based on the vouching mechanism.",
                null=True,
            ),
        ),
    ]
