# Generated by Django 4.0.8 on 2022-10-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_user_voting_right"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="voting_right",
        ),
        migrations.AddField(
            model_name="user",
            name="trust_score",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="The trust score assigned to the user based on the vouching mechanism.",
                null=True,
            ),
        ),
    ]
