# Generated by Django 4.0.8 on 2023-01-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_user_votingright_isnow_trustscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="settings",
            field=models.JSONField(
                blank=True, default=dict, help_text="The user' preferences."
            ),
        ),
    ]
