# Generated by Django 4.0.8 on 2023-01-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='user',
            name='comment_anonymously',
        ),
        migrations.RemoveField(
            model_name='user',
            name='degree_of_political_engagement',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_scholar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_demo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='moral_philosophy',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='user',
            name='orcid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='political_affiliation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='race',
        ),
        migrations.RemoveField(
            model_name='user',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='researchgate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='residence',
        ),
        migrations.RemoveField(
            model_name='user',
            name='show_my_profile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='show_online_presence',
        ),
        migrations.RemoveField(
            model_name='user',
            name='title',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='website',
        ),
        migrations.RemoveField(
            model_name='user',
            name='youtube',
        ),
    ]
