# Generated by Django 4.1.10 on 2023-07-06 08:41

from django.db import migrations


def update_notifications_lang(apps, before, after):
    User = apps.get_model("core", "User")

    for user in User.objects.filter(
        settings__contains={"general": {"notifications__lang": before}}
    ).iterator():
        user.settings["general"]["notifications__lang"] = after
        user.save(update_fields=["settings"])


def update_notifications_lang_forward(apps, schema_editor):
    """
    We want to save ISO 639-1 code in the database to ease the API usage by
    the front end or any API consumer.
    """
    update_notifications_lang(apps, "ENGLISH", "en")
    update_notifications_lang(apps, "FRENCH", "fr")


def update_notifications_lang_reverse(apps, schema_editor):
    update_notifications_lang(apps, "en", "ENGLISH")
    update_notifications_lang(apps, "fr", "FRENCH")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_user_avatar_remove_user_bio_and_more"),
    ]

    operations = [
        migrations.RunPython(update_notifications_lang_forward, update_notifications_lang_reverse),
    ]
