# Generated by Django 4.2.11 on 2024-06-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_update_notificatoins_lang_value"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE IF EXISTS default_cache_table SET UNLOGGED;",
            reverse_sql="ALTER TABLE IF EXISTS default_cache_table SET LOGGED;",
        ),
    ]
