# Generated by Django 4.2.14 on 2024-07-17 12:44

from django.db import migrations


def copy_setting(user, from_key, to_key):
    try:
        value = user.settings["videos"][from_key]
    except KeyError:
        return False

    user.settings["videos"][to_key] = value
    return True


def migrate_reco_settings_forward(apps, schema_editor):
    User = apps.get_model("core", "User")
    for user in User.objects.all():
        if "videos" not in user.settings:
            continue

        copied = map(
            copy_setting,
            [user] * 5,
            [
                "recommendations__default_date",
                "recommendations__default_languages",
                "recommendations__default_unsafe",
                "recommendations__default_exclude_compared_entities",
                "recommendations__default_languages",
            ],
            [
                "feed_foryou__date",
                "feed_foryou__languages",
                "feed_foryou__unsafe",
                "feed_foryou__exclude_compared_entities",
                "feed_topitems__languages",
            ],
        )

        if any(list(copied)):
            user.save(update_fields=["settings"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_use_unlogged_cache_table"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_reco_settings_forward, reverse_code=migrations.RunPython.noop
        ),
    ]
