/**
 * Tournesol API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TournesolApi);
  }
}(this, function(expect, TournesolApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TournesolApi.Disagreement();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Disagreement', function() {
    it('should create an instance of Disagreement', function() {
      // uncomment below and update the code to test Disagreement
      //var instane = new TournesolApi.Disagreement();
      //expect(instance).to.be.a(TournesolApi.Disagreement);
    });

    it('should have the property feature (base name: "feature")', function() {
      // uncomment below and update the code to test the property feature
      //var instane = new TournesolApi.Disagreement();
      //expect(instance).to.be();
    });

    it('should have the property video1VideoId (base name: "video_1__video_id")', function() {
      // uncomment below and update the code to test the property video1VideoId
      //var instane = new TournesolApi.Disagreement();
      //expect(instance).to.be();
    });

    it('should have the property video2VideoId (base name: "video_2__video_id")', function() {
      // uncomment below and update the code to test the property video2VideoId
      //var instane = new TournesolApi.Disagreement();
      //expect(instance).to.be();
    });

    it('should have the property modelScore (base name: "model_score")', function() {
      // uncomment below and update the code to test the property modelScore
      //var instane = new TournesolApi.Disagreement();
      //expect(instance).to.be();
    });

    it('should have the property ratingScore (base name: "rating_score")', function() {
      // uncomment below and update the code to test the property ratingScore
      //var instane = new TournesolApi.Disagreement();
      //expect(instance).to.be();
    });

    it('should have the property mse01 (base name: "mse_01")', function() {
      // uncomment below and update the code to test the property mse01
      //var instane = new TournesolApi.Disagreement();
      //expect(instance).to.be();
    });

  });

}));
